//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.Helper.PssimRoles {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entrada", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Entrada : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        private int Id_SistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UssistField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Id_Sistema {
            get {
                return this.Id_SistemaField;
            }
            set {
                if ((this.Id_SistemaField.Equals(value) != true)) {
                    this.Id_SistemaField = value;
                    this.RaisePropertyChanged("Id_Sistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Ussist {
            get {
                return this.UssistField;
            }
            set {
                if ((object.ReferenceEquals(this.UssistField, value) != true)) {
                    this.UssistField = value;
                    this.RaisePropertyChanged("Ussist");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PssimRoles.SistemaSoap")]
    public interface SistemaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento input del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Roles_Usuario_Sistema", ReplyAction="*")]
        Minvu.Snat.Helper.PssimRoles.Roles_Usuario_SistemaResponse Roles_Usuario_Sistema(Minvu.Snat.Helper.PssimRoles.Roles_Usuario_SistemaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Roles_Usuario_Sistema", ReplyAction="*")]
        System.Threading.Tasks.Task<Minvu.Snat.Helper.PssimRoles.Roles_Usuario_SistemaResponse> Roles_Usuario_SistemaAsync(Minvu.Snat.Helper.PssimRoles.Roles_Usuario_SistemaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Roles_Usuario_SistemaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Roles_Usuario_Sistema", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.Snat.Helper.PssimRoles.Roles_Usuario_SistemaRequestBody Body;
        
        public Roles_Usuario_SistemaRequest() {
        }
        
        public Roles_Usuario_SistemaRequest(Minvu.Snat.Helper.PssimRoles.Roles_Usuario_SistemaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Roles_Usuario_SistemaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Minvu.Snat.Helper.PssimRoles.Entrada input;
        
        public Roles_Usuario_SistemaRequestBody() {
        }
        
        public Roles_Usuario_SistemaRequestBody(Minvu.Snat.Helper.PssimRoles.Entrada input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Roles_Usuario_SistemaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Roles_Usuario_SistemaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.Snat.Helper.PssimRoles.Roles_Usuario_SistemaResponseBody Body;
        
        public Roles_Usuario_SistemaResponse() {
        }
        
        public Roles_Usuario_SistemaResponse(Minvu.Snat.Helper.PssimRoles.Roles_Usuario_SistemaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Roles_Usuario_SistemaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Roles_Usuario_SistemaResult;
        
        public Roles_Usuario_SistemaResponseBody() {
        }
        
        public Roles_Usuario_SistemaResponseBody(string Roles_Usuario_SistemaResult) {
            this.Roles_Usuario_SistemaResult = Roles_Usuario_SistemaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SistemaSoapChannel : Minvu.Snat.Helper.PssimRoles.SistemaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SistemaSoapClient : System.ServiceModel.ClientBase<Minvu.Snat.Helper.PssimRoles.SistemaSoap>, Minvu.Snat.Helper.PssimRoles.SistemaSoap {
        
        public SistemaSoapClient() {
        }
        
        public SistemaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SistemaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SistemaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SistemaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Minvu.Snat.Helper.PssimRoles.Roles_Usuario_SistemaResponse Minvu.Snat.Helper.PssimRoles.SistemaSoap.Roles_Usuario_Sistema(Minvu.Snat.Helper.PssimRoles.Roles_Usuario_SistemaRequest request) {
            return base.Channel.Roles_Usuario_Sistema(request);
        }
        
        public string Roles_Usuario_Sistema(Minvu.Snat.Helper.PssimRoles.Entrada input) {
            Minvu.Snat.Helper.PssimRoles.Roles_Usuario_SistemaRequest inValue = new Minvu.Snat.Helper.PssimRoles.Roles_Usuario_SistemaRequest();
            inValue.Body = new Minvu.Snat.Helper.PssimRoles.Roles_Usuario_SistemaRequestBody();
            inValue.Body.input = input;
            Minvu.Snat.Helper.PssimRoles.Roles_Usuario_SistemaResponse retVal = ((Minvu.Snat.Helper.PssimRoles.SistemaSoap)(this)).Roles_Usuario_Sistema(inValue);
            return retVal.Body.Roles_Usuario_SistemaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Minvu.Snat.Helper.PssimRoles.Roles_Usuario_SistemaResponse> Minvu.Snat.Helper.PssimRoles.SistemaSoap.Roles_Usuario_SistemaAsync(Minvu.Snat.Helper.PssimRoles.Roles_Usuario_SistemaRequest request) {
            return base.Channel.Roles_Usuario_SistemaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Minvu.Snat.Helper.PssimRoles.Roles_Usuario_SistemaResponse> Roles_Usuario_SistemaAsync(Minvu.Snat.Helper.PssimRoles.Entrada input) {
            Minvu.Snat.Helper.PssimRoles.Roles_Usuario_SistemaRequest inValue = new Minvu.Snat.Helper.PssimRoles.Roles_Usuario_SistemaRequest();
            inValue.Body = new Minvu.Snat.Helper.PssimRoles.Roles_Usuario_SistemaRequestBody();
            inValue.Body.input = input;
            return ((Minvu.Snat.Helper.PssimRoles.SistemaSoap)(this)).Roles_Usuario_SistemaAsync(inValue);
        }
    }
}
