//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTORIZACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AUTORIZACION()
        {
            this.TIPO_AUTORIZACION = new HashSet<TIPO_AUTORIZACION>();
        }
    
        public long IDAUTORIZACION { get; set; }
        public Nullable<long> IDMAESTROESTADOAUTORIZACION { get; set; }
        public Nullable<bool> ESPECIALAUTORIZACION { get; set; }
        public Nullable<int> CANTIDADPROYECTOSAUTORIZACION { get; set; }
        public Nullable<int> CANTIDADSOLICITUDPAGOAUTORIZACION { get; set; }
        public Nullable<decimal> MONTOTOTALAUTORIZACION { get; set; }
        public string USUARIORESPONSABLEAUTORIZACION { get; set; }
        public Nullable<System.DateTime> FECHAINGRESOAUTORIZACION { get; set; }
        public Nullable<long> CODIGOREGIONAUTORIZACION { get; set; }
        public Nullable<long> NUMEROAUTORIZACION { get; set; }
        public Nullable<long> IDMAESTROMODALIDAD { get; set; }
        public Nullable<long> IDMAESTROPROGRAMA { get; set; }
        public Nullable<long> IDMAESTROTIPOLOGIA { get; set; }
        public Nullable<long> IDMAESTROTITULO { get; set; }
        public Nullable<long> IDPROVEEDOR { get; set; }
        public Nullable<System.DateTime> FECHAUFAUTORIZACION { get; set; }
        public Nullable<System.DateTime> FECHAINYECCIONAUTORIZACION { get; set; }
        public Nullable<long> VALORUFPESOAUTORIZACION { get; set; }
    
        public virtual MAESTRO_ESTADO_AUTORIZACION MAESTRO_ESTADO_AUTORIZACION { get; set; }
        public virtual MAESTRO_MODALIDAD MAESTRO_MODALIDAD { get; set; }
        public virtual MAESTRO_PROGRAMA MAESTRO_PROGRAMA { get; set; }
        public virtual MAESTRO_TIPOLOGIA MAESTRO_TIPOLOGIA { get; set; }
        public virtual MAESTRO_TITULO MAESTRO_TITULO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_AUTORIZACION> TIPO_AUTORIZACION { get; set; }
    }
}
