//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENEFICIARIO
    {
        public long IDBENEFICIARIO { get; set; }
        public Nullable<long> IDDIRECCION { get; set; }
        public Nullable<long> IDINFORMACIONPROYECTO { get; set; }
        public Nullable<int> RUTBENEFICIARIO { get; set; }
        public string DIGITOVERIFICADORBENEFICIARIO { get; set; }
        public string NOMBREBENEFICIARIO { get; set; }
        public string APELLIDOPATERNOBENEFICIARIO { get; set; }
        public string APELLIDOMATERNOBENEFICIARIO { get; set; }
        public Nullable<bool> ESTADOBENEFICIARIO { get; set; }
        public Nullable<long> IDMAESTROALTERNATIVAPOSTULACION { get; set; }
        public Nullable<System.DateTime> FECHAINICIOVIGENCIASUBSIDIOBENEFICIARIO { get; set; }
        public Nullable<System.DateTime> FECHATERMINOVIGENCIASUBSIDIOBENEFICIARIO { get; set; }
        public Nullable<System.DateTime> FECHAADSCRIPCIONPROYECTOBENEFICIARIO { get; set; }
        public Nullable<long> IDMAESTROESTADOBENEFICIARIO { get; set; }
    
        public virtual DIRECCION DIRECCION { get; set; }
        public virtual INFORMACION_PROYECTO INFORMACION_PROYECTO { get; set; }
        public virtual MAESTRO_ALTERNATIVA_POSTULACION MAESTRO_ALTERNATIVA_POSTULACION { get; set; }
        public virtual MAESTRO_ESTADO_BENEFICIARIO MAESTRO_ESTADO_BENEFICIARIO { get; set; }
    }
}
