//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARACTERISTICAS_ESPECIALES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARACTERISTICAS_ESPECIALES()
        {
            this.TIPO_SERVICIO_PARCIALIDAD_CARACTERISTICA = new HashSet<TIPO_SERVICIO_PARCIALIDAD_CARACTERISTICA>();
            this.SOLICITUD_PAGO = new HashSet<SOLICITUD_PAGO>();
            this.TIPO_INCREMENTO = new HashSet<TIPO_INCREMENTO>();
        }
    
        public long IDCARACTERISTICASESPECIALES { get; set; }
        public Nullable<long> IDMAESTROPROGRAMA { get; set; }
        public Nullable<long> IDMAESTROMODALIDAD { get; set; }
        public Nullable<long> IDMAESTROTIPOLOGIA { get; set; }
        public Nullable<long> IDINFORMACIONPROYECTO { get; set; }
        public Nullable<long> IDMAESTROCLASE { get; set; }
        public Nullable<long> IDMAESTROSUBMODALIDAD { get; set; }
    
        public virtual INFORMACION_PROYECTO INFORMACION_PROYECTO { get; set; }
        public virtual MAESTRO_TIPOLOGIA MAESTRO_TIPOLOGIA { get; set; }
        public virtual MAESTRO_CLASE MAESTRO_CLASE { get; set; }
        public virtual MAESTRO_MODALIDAD MAESTRO_MODALIDAD { get; set; }
        public virtual MAESTRO_PROGRAMA MAESTRO_PROGRAMA { get; set; }
        public virtual MAESTRO_SUB_MODALIDAD MAESTRO_SUB_MODALIDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_SERVICIO_PARCIALIDAD_CARACTERISTICA> TIPO_SERVICIO_PARCIALIDAD_CARACTERISTICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD_PAGO> SOLICITUD_PAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_INCREMENTO> TIPO_INCREMENTO { get; set; }
    }
}
