//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMUNA
    {
        public int REG_ID { get; set; }
        public int PRV_ID { get; set; }
        public int COM_ID { get; set; }
        public string COM_DES { get; set; }
        public Nullable<bool> ZONA_SATURADA { get; set; }
        public Nullable<int> ZONA_TERMICA { get; set; }
        public Nullable<int> COM_ID_SII { get; set; }
        public Nullable<bool> COM_QTY_HAB { get; set; }
        public Nullable<bool> COM_QTY_HAB_EXCP { get; set; }
        public Nullable<int> COM_TRA { get; set; }
        public Nullable<int> COM_MAX_CVS_ESP_TII { get; set; }
        public Nullable<int> COM_QTY_NUM_HAB { get; set; }
    
        public virtual PROVINCIA PROVINCIA { get; set; }
    }
}
