//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO_ATP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTRATO_ATP()
        {
            this.SOLICITUD_PAGO_ATP = new HashSet<SOLICITUD_PAGO_ATP>();
            this.TIPO_SERVICIOS_CONTRATO = new HashSet<TIPO_SERVICIOS_CONTRATO>();
        }
    
        public long IDCONTRATOATP { get; set; }
        public Nullable<long> IDTERRITORIOCONTRATO { get; set; }
        public Nullable<long> IDPROPIEDADTERRENO { get; set; }
        public Nullable<long> IDPROVEEDOR { get; set; }
        public Nullable<long> IDMAESTROTIPOSERVICIOIGT { get; set; }
        public Nullable<long> NUMERORESOLUCIONCONTRATOATP { get; set; }
        public byte[] ARCHIVOCONTRATOATP { get; set; }
        public Nullable<int> AGNOPRESUPUESTOCONTRATOATP { get; set; }
        public string OBSERVACIONCONTRATOATP { get; set; }
        public Nullable<System.DateTime> FECHACREACIONCONTRATOATP { get; set; }
        public Nullable<System.DateTime> FECHAACTUALIZACIONCONTRATOATP { get; set; }
        public string PRODUCTOCONTRATOATP { get; set; }
        public string DESCRIPCIONPRODUCTOCONTRATOATP { get; set; }
        public string USUARIOCONTRATOATP { get; set; }
        public Nullable<int> PLAZOEJECUCIONCONTRATOATP { get; set; }
        public Nullable<System.DateTime> FECHAINICIOCONTRATOATP { get; set; }
        public string NOMBREARCHIVOCONTRATOATP { get; set; }
        public Nullable<System.DateTime> FECHARESOLUCIONCONTRATOATP { get; set; }
        public Nullable<long> MONTOCONTRATOCONTRATOATP { get; set; }
        public Nullable<long> IDMAESTROTIPOPROVEEDOR { get; set; }
        public Nullable<long> IDMAESTROESTADOCONTRATO { get; set; }
    
        public virtual MAESTRO_ESTADO_CONTRATO MAESTRO_ESTADO_CONTRATO { get; set; }
        public virtual MAESTRO_TIPO_PROVEEDOR MAESTRO_TIPO_PROVEEDOR { get; set; }
        public virtual MAESTRO_TIPO_SERVICIO_IGT MAESTRO_TIPO_SERVICIO_IGT { get; set; }
        public virtual PROPIEDAD_TERRENO PROPIEDAD_TERRENO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual TERRITORIO_CONTRATO TERRITORIO_CONTRATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD_PAGO_ATP> SOLICITUD_PAGO_ATP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_SERVICIOS_CONTRATO> TIPO_SERVICIOS_CONTRATO { get; set; }
    }
}
