//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONVALIDACION_PROGRAMA_SISTEMA
    {
        public long IDCONVALIDACIONPROGRAMASISTEMA { get; set; }
        public Nullable<long> IDMAESTROPROGRAMA { get; set; }
        public Nullable<long> IDMAESTROSISTEMA { get; set; }
        public Nullable<long> CODIGOPROGRAMAEXTERNOCONVALIDACIONPROGRAMASISTEMA { get; set; }
        public Nullable<bool> ESTADOMAESTROPROGRAMACONVALIDACIONPROGRAMASISTEMA { get; set; }
    
        public virtual MAESTRO_PROGRAMA MAESTRO_PROGRAMA { get; set; }
        public virtual MAESTRO_SISTEMA MAESTRO_SISTEMA { get; set; }
    }
}
