//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_SNAT_VEntities : DbContext
    {
        public DB_SNAT_VEntities()
            : base("name=DB_SNAT_VEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTORIZACION> AUTORIZACION { get; set; }
        public virtual DbSet<BENEFICIARIO> BENEFICIARIO { get; set; }
        public virtual DbSet<CARACTERISTICAS_ESPECIALES> CARACTERISTICAS_ESPECIALES { get; set; }
        public virtual DbSet<CONTRATO_ATP> CONTRATO_ATP { get; set; }
        public virtual DbSet<CONVALIDACION_PROGRAMA_SISTEMA> CONVALIDACION_PROGRAMA_SISTEMA { get; set; }
        public virtual DbSet<DIRECCION> DIRECCION { get; set; }
        public virtual DbSet<HOMOLOGACION_INFORMACION_SISTEMA> HOMOLOGACION_INFORMACION_SISTEMA { get; set; }
        public virtual DbSet<INFORMACION_PROYECTO> INFORMACION_PROYECTO { get; set; }
        public virtual DbSet<INFORMACION_PROYECTO_SOLICITUD> INFORMACION_PROYECTO_SOLICITUD { get; set; }
        public virtual DbSet<MAESTRO_ALTERNATIVA_POSTULACION> MAESTRO_ALTERNATIVA_POSTULACION { get; set; }
        public virtual DbSet<MAESTRO_BANCO> MAESTRO_BANCO { get; set; }
        public virtual DbSet<MAESTRO_CLASE> MAESTRO_CLASE { get; set; }
        public virtual DbSet<MAESTRO_ESTADO_AUTORIZACION> MAESTRO_ESTADO_AUTORIZACION { get; set; }
        public virtual DbSet<MAESTRO_ESTADO_BENEFICIARIO> MAESTRO_ESTADO_BENEFICIARIO { get; set; }
        public virtual DbSet<MAESTRO_ESTADO_BENEFICIO> MAESTRO_ESTADO_BENEFICIO { get; set; }
        public virtual DbSet<MAESTRO_ESTADO_CONTRATO> MAESTRO_ESTADO_CONTRATO { get; set; }
        public virtual DbSet<MAESTRO_ESTADO_PROYECTO> MAESTRO_ESTADO_PROYECTO { get; set; }
        public virtual DbSet<MAESTRO_ESTADO_SOLICITUD> MAESTRO_ESTADO_SOLICITUD { get; set; }
        public virtual DbSet<MAESTRO_INCREMENTO> MAESTRO_INCREMENTO { get; set; }
        public virtual DbSet<MAESTRO_INFORMACION_SISTEMA_EXTERNO> MAESTRO_INFORMACION_SISTEMA_EXTERNO { get; set; }
        public virtual DbSet<MAESTRO_LLAMADO> MAESTRO_LLAMADO { get; set; }
        public virtual DbSet<MAESTRO_MODALIDAD> MAESTRO_MODALIDAD { get; set; }
        public virtual DbSet<MAESTRO_PARCIALIDAD> MAESTRO_PARCIALIDAD { get; set; }
        public virtual DbSet<MAESTRO_PROGRAMA> MAESTRO_PROGRAMA { get; set; }
        public virtual DbSet<MAESTRO_RESOLUCION> MAESTRO_RESOLUCION { get; set; }
        public virtual DbSet<MAESTRO_SERVICIO> MAESTRO_SERVICIO { get; set; }
        public virtual DbSet<MAESTRO_SISTEMA> MAESTRO_SISTEMA { get; set; }
        public virtual DbSet<MAESTRO_SUB_MODALIDAD> MAESTRO_SUB_MODALIDAD { get; set; }
        public virtual DbSet<MAESTRO_TIPO_DESTINO_PAGO> MAESTRO_TIPO_DESTINO_PAGO { get; set; }
        public virtual DbSet<MAESTRO_TIPO_INGRESO> MAESTRO_TIPO_INGRESO { get; set; }
        public virtual DbSet<MAESTRO_TIPO_PAGO> MAESTRO_TIPO_PAGO { get; set; }
        public virtual DbSet<MAESTRO_TIPO_PROVEEDOR> MAESTRO_TIPO_PROVEEDOR { get; set; }
        public virtual DbSet<MAESTRO_TIPO_PROVEEDOR_SISTEMA> MAESTRO_TIPO_PROVEEDOR_SISTEMA { get; set; }
        public virtual DbSet<MAESTRO_TIPO_SERVICIO_IGT> MAESTRO_TIPO_SERVICIO_IGT { get; set; }
        public virtual DbSet<MAESTRO_TIPOLOGIA> MAESTRO_TIPOLOGIA { get; set; }
        public virtual DbSet<MAESTRO_TITULO> MAESTRO_TITULO { get; set; }
        public virtual DbSet<MODIFICACION_ESTADO_SOLICITUD> MODIFICACION_ESTADO_SOLICITUD { get; set; }
        public virtual DbSet<PRESUPUESTO_REGIONAL> PRESUPUESTO_REGIONAL { get; set; }
        public virtual DbSet<PROPIEDAD_TERRENO> PROPIEDAD_TERRENO { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<RESOLUCION_PRESUPUESTARIA> RESOLUCION_PRESUPUESTARIA { get; set; }
        public virtual DbSet<SERVICIO_PARCIALIDAD> SERVICIO_PARCIALIDAD { get; set; }
        public virtual DbSet<SOLICITUD_AUTORIZACION> SOLICITUD_AUTORIZACION { get; set; }
        public virtual DbSet<SOLICITUD_PAGO> SOLICITUD_PAGO { get; set; }
        public virtual DbSet<SOLICITUD_PAGO_ATP> SOLICITUD_PAGO_ATP { get; set; }
        public virtual DbSet<SUB_MODALIDAD_PARCIALIDAD> SUB_MODALIDAD_PARCIALIDAD { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TERRITORIO_CONTRATO> TERRITORIO_CONTRATO { get; set; }
        public virtual DbSet<TIPO_ACTIVIDAD_MONTO> TIPO_ACTIVIDAD_MONTO { get; set; }
        public virtual DbSet<TIPO_AUTORIZACION> TIPO_AUTORIZACION { get; set; }
        public virtual DbSet<TIPO_INCREMENTO> TIPO_INCREMENTO { get; set; }
        public virtual DbSet<TIPO_PARCIALIDAD> TIPO_PARCIALIDAD { get; set; }
        public virtual DbSet<TIPO_PROVEEDOR_INFORMACION_PROYECTO> TIPO_PROVEEDOR_INFORMACION_PROYECTO { get; set; }
        public virtual DbSet<TIPO_SERVICIO> TIPO_SERVICIO { get; set; }
        public virtual DbSet<TIPO_SERVICIO_PARCIALIDAD_CARACTERISTICA> TIPO_SERVICIO_PARCIALIDAD_CARACTERISTICA { get; set; }
        public virtual DbSet<TIPO_SERVICIOS_CONTRATO> TIPO_SERVICIOS_CONTRATO { get; set; }
        public virtual DbSet<TIPOLOGIA_SERVICIO> TIPOLOGIA_SERVICIO { get; set; }
    
        public virtual ObjectResult<BUSQUEDA_AUTORIZACION_DE_PAGO_Result> BUSQUEDA_AUTORIZACION_DE_PAGO(Nullable<int> cODIGOPROYECTO, Nullable<long> iDMAESTROPROGRAMA, Nullable<long> iDMAESTROTIPOLOGIA, Nullable<long> iDAUTORIZACION, string nOMBREPROVEEDOR, Nullable<long> iDMAESTROMODALIDAD, Nullable<long> iDMAESTROLLAMADO, Nullable<int> cODIGOREGIONDIRECCION, Nullable<int> cODIGOPROVINCIADIRECCION, Nullable<int> cODIGOCOMUNADIRECCION, Nullable<long> iDMAESTROSERVICIO, Nullable<long> iDMAESTROTIPOPROVEEDOR, Nullable<long> iDMAESTROTITULO, Nullable<long> iDMAESTROESTADOAUTORIZACION)
        {
            var cODIGOPROYECTOParameter = cODIGOPROYECTO.HasValue ?
                new ObjectParameter("CODIGOPROYECTO", cODIGOPROYECTO) :
                new ObjectParameter("CODIGOPROYECTO", typeof(int));
    
            var iDMAESTROPROGRAMAParameter = iDMAESTROPROGRAMA.HasValue ?
                new ObjectParameter("IDMAESTROPROGRAMA", iDMAESTROPROGRAMA) :
                new ObjectParameter("IDMAESTROPROGRAMA", typeof(long));
    
            var iDMAESTROTIPOLOGIAParameter = iDMAESTROTIPOLOGIA.HasValue ?
                new ObjectParameter("IDMAESTROTIPOLOGIA", iDMAESTROTIPOLOGIA) :
                new ObjectParameter("IDMAESTROTIPOLOGIA", typeof(long));
    
            var iDAUTORIZACIONParameter = iDAUTORIZACION.HasValue ?
                new ObjectParameter("IDAUTORIZACION", iDAUTORIZACION) :
                new ObjectParameter("IDAUTORIZACION", typeof(long));
    
            var nOMBREPROVEEDORParameter = nOMBREPROVEEDOR != null ?
                new ObjectParameter("NOMBREPROVEEDOR", nOMBREPROVEEDOR) :
                new ObjectParameter("NOMBREPROVEEDOR", typeof(string));
    
            var iDMAESTROMODALIDADParameter = iDMAESTROMODALIDAD.HasValue ?
                new ObjectParameter("IDMAESTROMODALIDAD", iDMAESTROMODALIDAD) :
                new ObjectParameter("IDMAESTROMODALIDAD", typeof(long));
    
            var iDMAESTROLLAMADOParameter = iDMAESTROLLAMADO.HasValue ?
                new ObjectParameter("IDMAESTROLLAMADO", iDMAESTROLLAMADO) :
                new ObjectParameter("IDMAESTROLLAMADO", typeof(long));
    
            var cODIGOREGIONDIRECCIONParameter = cODIGOREGIONDIRECCION.HasValue ?
                new ObjectParameter("CODIGOREGIONDIRECCION", cODIGOREGIONDIRECCION) :
                new ObjectParameter("CODIGOREGIONDIRECCION", typeof(int));
    
            var cODIGOPROVINCIADIRECCIONParameter = cODIGOPROVINCIADIRECCION.HasValue ?
                new ObjectParameter("CODIGOPROVINCIADIRECCION", cODIGOPROVINCIADIRECCION) :
                new ObjectParameter("CODIGOPROVINCIADIRECCION", typeof(int));
    
            var cODIGOCOMUNADIRECCIONParameter = cODIGOCOMUNADIRECCION.HasValue ?
                new ObjectParameter("CODIGOCOMUNADIRECCION", cODIGOCOMUNADIRECCION) :
                new ObjectParameter("CODIGOCOMUNADIRECCION", typeof(int));
    
            var iDMAESTROSERVICIOParameter = iDMAESTROSERVICIO.HasValue ?
                new ObjectParameter("IDMAESTROSERVICIO", iDMAESTROSERVICIO) :
                new ObjectParameter("IDMAESTROSERVICIO", typeof(long));
    
            var iDMAESTROTIPOPROVEEDORParameter = iDMAESTROTIPOPROVEEDOR.HasValue ?
                new ObjectParameter("IDMAESTROTIPOPROVEEDOR", iDMAESTROTIPOPROVEEDOR) :
                new ObjectParameter("IDMAESTROTIPOPROVEEDOR", typeof(long));
    
            var iDMAESTROTITULOParameter = iDMAESTROTITULO.HasValue ?
                new ObjectParameter("IDMAESTROTITULO", iDMAESTROTITULO) :
                new ObjectParameter("IDMAESTROTITULO", typeof(long));
    
            var iDMAESTROESTADOAUTORIZACIONParameter = iDMAESTROESTADOAUTORIZACION.HasValue ?
                new ObjectParameter("IDMAESTROESTADOAUTORIZACION", iDMAESTROESTADOAUTORIZACION) :
                new ObjectParameter("IDMAESTROESTADOAUTORIZACION", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BUSQUEDA_AUTORIZACION_DE_PAGO_Result>("BUSQUEDA_AUTORIZACION_DE_PAGO", cODIGOPROYECTOParameter, iDMAESTROPROGRAMAParameter, iDMAESTROTIPOLOGIAParameter, iDAUTORIZACIONParameter, nOMBREPROVEEDORParameter, iDMAESTROMODALIDADParameter, iDMAESTROLLAMADOParameter, cODIGOREGIONDIRECCIONParameter, cODIGOPROVINCIADIRECCIONParameter, cODIGOCOMUNADIRECCIONParameter, iDMAESTROSERVICIOParameter, iDMAESTROTIPOPROVEEDORParameter, iDMAESTROTITULOParameter, iDMAESTROESTADOAUTORIZACIONParameter);
        }
    
        public virtual ObjectResult<BUSQUEDA_DETALLE_AUTORIZACION_DE_PAGO_GRILLA_Result> BUSQUEDA_DETALLE_AUTORIZACION_DE_PAGO_GRILLA(Nullable<long> iDAUTORIZACION, Nullable<long> iDTIPOPROVEEDOR)
        {
            var iDAUTORIZACIONParameter = iDAUTORIZACION.HasValue ?
                new ObjectParameter("IDAUTORIZACION", iDAUTORIZACION) :
                new ObjectParameter("IDAUTORIZACION", typeof(long));
    
            var iDTIPOPROVEEDORParameter = iDTIPOPROVEEDOR.HasValue ?
                new ObjectParameter("IDTIPOPROVEEDOR", iDTIPOPROVEEDOR) :
                new ObjectParameter("IDTIPOPROVEEDOR", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BUSQUEDA_DETALLE_AUTORIZACION_DE_PAGO_GRILLA_Result>("BUSQUEDA_DETALLE_AUTORIZACION_DE_PAGO_GRILLA", iDAUTORIZACIONParameter, iDTIPOPROVEEDORParameter);
        }
    
        public virtual ObjectResult<CONSULTA_ACTIVIDADES_CONTRATO_Result> CONSULTA_ACTIVIDADES_CONTRATO(Nullable<long> iDCONTRATO)
        {
            var iDCONTRATOParameter = iDCONTRATO.HasValue ?
                new ObjectParameter("IDCONTRATO", iDCONTRATO) :
                new ObjectParameter("IDCONTRATO", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULTA_ACTIVIDADES_CONTRATO_Result>("CONSULTA_ACTIVIDADES_CONTRATO", iDCONTRATOParameter);
        }
    
        public virtual ObjectResult<ELIMINA_CONTRATO_Result> ELIMINA_CONTRATO(Nullable<long> iDCONTRATO)
        {
            var iDCONTRATOParameter = iDCONTRATO.HasValue ?
                new ObjectParameter("IDCONTRATO", iDCONTRATO) :
                new ObjectParameter("IDCONTRATO", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ELIMINA_CONTRATO_Result>("ELIMINA_CONTRATO", iDCONTRATOParameter);
        }
    
        public virtual ObjectResult<ELIMINA_SOLICITUD_Result> ELIMINA_SOLICITUD(Nullable<long> iDSOLICITUD)
        {
            var iDSOLICITUDParameter = iDSOLICITUD.HasValue ?
                new ObjectParameter("IDSOLICITUD", iDSOLICITUD) :
                new ObjectParameter("IDSOLICITUD", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ELIMINA_SOLICITUD_Result>("ELIMINA_SOLICITUD", iDSOLICITUDParameter);
        }
    
        public virtual ObjectResult<INSERTA_CONTRATO_SAT_SET_Result> INSERTA_CONTRATO_SAT_SET(Nullable<int> rUTPROVEEDOR, string dVPROVEEDOR, string nOMBREPROVEEDOR, Nullable<int> tIPOPROVEEDOR, Nullable<int> aNNOCONTRATO, Nullable<int> cODIGOREGION, Nullable<int> cODIGOPROVINCIA, Nullable<int> cODIGOCOMUNA, Nullable<int> pLAZOEJECUCION, string pROPIEDADTERRENO, Nullable<long> nUMERORESOLUCION, Nullable<System.DateTime> fECHARESOLUCIONCONTRATO, Nullable<System.DateTime> fECHAINICIOCONTRATO, string nOMBREARCHIVO, Nullable<long> iDTIPOSERVICIO, Nullable<int> eSTADOTIPOSERVICIO1, Nullable<int> eSTADOTIPOSERVICIO2, Nullable<int> eSTADOTIPOSERVICIO3, Nullable<int> eSTADOTIPOSERVICIO4, Nullable<int> eSTADOTIPOSERVICIO5, Nullable<int> eSTADOTIPOSERVICIO6, Nullable<int> eSTADOTIPOSERVICIO7, string nOMBRETIPOSERVICIO8, string pRODUCTOCONTRATO, string dESCRIPCIONPRODUCTO, Nullable<long> mONTOCONTRATO, string oBSERVACIONCONTRATO, string uSUARIO)
        {
            var rUTPROVEEDORParameter = rUTPROVEEDOR.HasValue ?
                new ObjectParameter("RUTPROVEEDOR", rUTPROVEEDOR) :
                new ObjectParameter("RUTPROVEEDOR", typeof(int));
    
            var dVPROVEEDORParameter = dVPROVEEDOR != null ?
                new ObjectParameter("DVPROVEEDOR", dVPROVEEDOR) :
                new ObjectParameter("DVPROVEEDOR", typeof(string));
    
            var nOMBREPROVEEDORParameter = nOMBREPROVEEDOR != null ?
                new ObjectParameter("NOMBREPROVEEDOR", nOMBREPROVEEDOR) :
                new ObjectParameter("NOMBREPROVEEDOR", typeof(string));
    
            var tIPOPROVEEDORParameter = tIPOPROVEEDOR.HasValue ?
                new ObjectParameter("TIPOPROVEEDOR", tIPOPROVEEDOR) :
                new ObjectParameter("TIPOPROVEEDOR", typeof(int));
    
            var aNNOCONTRATOParameter = aNNOCONTRATO.HasValue ?
                new ObjectParameter("ANNOCONTRATO", aNNOCONTRATO) :
                new ObjectParameter("ANNOCONTRATO", typeof(int));
    
            var cODIGOREGIONParameter = cODIGOREGION.HasValue ?
                new ObjectParameter("CODIGOREGION", cODIGOREGION) :
                new ObjectParameter("CODIGOREGION", typeof(int));
    
            var cODIGOPROVINCIAParameter = cODIGOPROVINCIA.HasValue ?
                new ObjectParameter("CODIGOPROVINCIA", cODIGOPROVINCIA) :
                new ObjectParameter("CODIGOPROVINCIA", typeof(int));
    
            var cODIGOCOMUNAParameter = cODIGOCOMUNA.HasValue ?
                new ObjectParameter("CODIGOCOMUNA", cODIGOCOMUNA) :
                new ObjectParameter("CODIGOCOMUNA", typeof(int));
    
            var pLAZOEJECUCIONParameter = pLAZOEJECUCION.HasValue ?
                new ObjectParameter("PLAZOEJECUCION", pLAZOEJECUCION) :
                new ObjectParameter("PLAZOEJECUCION", typeof(int));
    
            var pROPIEDADTERRENOParameter = pROPIEDADTERRENO != null ?
                new ObjectParameter("PROPIEDADTERRENO", pROPIEDADTERRENO) :
                new ObjectParameter("PROPIEDADTERRENO", typeof(string));
    
            var nUMERORESOLUCIONParameter = nUMERORESOLUCION.HasValue ?
                new ObjectParameter("NUMERORESOLUCION", nUMERORESOLUCION) :
                new ObjectParameter("NUMERORESOLUCION", typeof(long));
    
            var fECHARESOLUCIONCONTRATOParameter = fECHARESOLUCIONCONTRATO.HasValue ?
                new ObjectParameter("FECHARESOLUCIONCONTRATO", fECHARESOLUCIONCONTRATO) :
                new ObjectParameter("FECHARESOLUCIONCONTRATO", typeof(System.DateTime));
    
            var fECHAINICIOCONTRATOParameter = fECHAINICIOCONTRATO.HasValue ?
                new ObjectParameter("FECHAINICIOCONTRATO", fECHAINICIOCONTRATO) :
                new ObjectParameter("FECHAINICIOCONTRATO", typeof(System.DateTime));
    
            var nOMBREARCHIVOParameter = nOMBREARCHIVO != null ?
                new ObjectParameter("NOMBREARCHIVO", nOMBREARCHIVO) :
                new ObjectParameter("NOMBREARCHIVO", typeof(string));
    
            var iDTIPOSERVICIOParameter = iDTIPOSERVICIO.HasValue ?
                new ObjectParameter("IDTIPOSERVICIO", iDTIPOSERVICIO) :
                new ObjectParameter("IDTIPOSERVICIO", typeof(long));
    
            var eSTADOTIPOSERVICIO1Parameter = eSTADOTIPOSERVICIO1.HasValue ?
                new ObjectParameter("ESTADOTIPOSERVICIO1", eSTADOTIPOSERVICIO1) :
                new ObjectParameter("ESTADOTIPOSERVICIO1", typeof(int));
    
            var eSTADOTIPOSERVICIO2Parameter = eSTADOTIPOSERVICIO2.HasValue ?
                new ObjectParameter("ESTADOTIPOSERVICIO2", eSTADOTIPOSERVICIO2) :
                new ObjectParameter("ESTADOTIPOSERVICIO2", typeof(int));
    
            var eSTADOTIPOSERVICIO3Parameter = eSTADOTIPOSERVICIO3.HasValue ?
                new ObjectParameter("ESTADOTIPOSERVICIO3", eSTADOTIPOSERVICIO3) :
                new ObjectParameter("ESTADOTIPOSERVICIO3", typeof(int));
    
            var eSTADOTIPOSERVICIO4Parameter = eSTADOTIPOSERVICIO4.HasValue ?
                new ObjectParameter("ESTADOTIPOSERVICIO4", eSTADOTIPOSERVICIO4) :
                new ObjectParameter("ESTADOTIPOSERVICIO4", typeof(int));
    
            var eSTADOTIPOSERVICIO5Parameter = eSTADOTIPOSERVICIO5.HasValue ?
                new ObjectParameter("ESTADOTIPOSERVICIO5", eSTADOTIPOSERVICIO5) :
                new ObjectParameter("ESTADOTIPOSERVICIO5", typeof(int));
    
            var eSTADOTIPOSERVICIO6Parameter = eSTADOTIPOSERVICIO6.HasValue ?
                new ObjectParameter("ESTADOTIPOSERVICIO6", eSTADOTIPOSERVICIO6) :
                new ObjectParameter("ESTADOTIPOSERVICIO6", typeof(int));
    
            var eSTADOTIPOSERVICIO7Parameter = eSTADOTIPOSERVICIO7.HasValue ?
                new ObjectParameter("ESTADOTIPOSERVICIO7", eSTADOTIPOSERVICIO7) :
                new ObjectParameter("ESTADOTIPOSERVICIO7", typeof(int));
    
            var nOMBRETIPOSERVICIO8Parameter = nOMBRETIPOSERVICIO8 != null ?
                new ObjectParameter("NOMBRETIPOSERVICIO8", nOMBRETIPOSERVICIO8) :
                new ObjectParameter("NOMBRETIPOSERVICIO8", typeof(string));
    
            var pRODUCTOCONTRATOParameter = pRODUCTOCONTRATO != null ?
                new ObjectParameter("PRODUCTOCONTRATO", pRODUCTOCONTRATO) :
                new ObjectParameter("PRODUCTOCONTRATO", typeof(string));
    
            var dESCRIPCIONPRODUCTOParameter = dESCRIPCIONPRODUCTO != null ?
                new ObjectParameter("DESCRIPCIONPRODUCTO", dESCRIPCIONPRODUCTO) :
                new ObjectParameter("DESCRIPCIONPRODUCTO", typeof(string));
    
            var mONTOCONTRATOParameter = mONTOCONTRATO.HasValue ?
                new ObjectParameter("MONTOCONTRATO", mONTOCONTRATO) :
                new ObjectParameter("MONTOCONTRATO", typeof(long));
    
            var oBSERVACIONCONTRATOParameter = oBSERVACIONCONTRATO != null ?
                new ObjectParameter("OBSERVACIONCONTRATO", oBSERVACIONCONTRATO) :
                new ObjectParameter("OBSERVACIONCONTRATO", typeof(string));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<INSERTA_CONTRATO_SAT_SET_Result>("INSERTA_CONTRATO_SAT_SET", rUTPROVEEDORParameter, dVPROVEEDORParameter, nOMBREPROVEEDORParameter, tIPOPROVEEDORParameter, aNNOCONTRATOParameter, cODIGOREGIONParameter, cODIGOPROVINCIAParameter, cODIGOCOMUNAParameter, pLAZOEJECUCIONParameter, pROPIEDADTERRENOParameter, nUMERORESOLUCIONParameter, fECHARESOLUCIONCONTRATOParameter, fECHAINICIOCONTRATOParameter, nOMBREARCHIVOParameter, iDTIPOSERVICIOParameter, eSTADOTIPOSERVICIO1Parameter, eSTADOTIPOSERVICIO2Parameter, eSTADOTIPOSERVICIO3Parameter, eSTADOTIPOSERVICIO4Parameter, eSTADOTIPOSERVICIO5Parameter, eSTADOTIPOSERVICIO6Parameter, eSTADOTIPOSERVICIO7Parameter, nOMBRETIPOSERVICIO8Parameter, pRODUCTOCONTRATOParameter, dESCRIPCIONPRODUCTOParameter, mONTOCONTRATOParameter, oBSERVACIONCONTRATOParameter, uSUARIOParameter);
        }
    
        public virtual ObjectResult<INSERTA_GENERACION_AUTORIZACION_PAGO_Result> INSERTA_GENERACION_AUTORIZACION_PAGO(string sOLICITUDPAGOLIST, string uSUARIORESPONSABLE)
        {
            var sOLICITUDPAGOLISTParameter = sOLICITUDPAGOLIST != null ?
                new ObjectParameter("SOLICITUDPAGOLIST", sOLICITUDPAGOLIST) :
                new ObjectParameter("SOLICITUDPAGOLIST", typeof(string));
    
            var uSUARIORESPONSABLEParameter = uSUARIORESPONSABLE != null ?
                new ObjectParameter("USUARIORESPONSABLE", uSUARIORESPONSABLE) :
                new ObjectParameter("USUARIORESPONSABLE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<INSERTA_GENERACION_AUTORIZACION_PAGO_Result>("INSERTA_GENERACION_AUTORIZACION_PAGO", sOLICITUDPAGOLISTParameter, uSUARIORESPONSABLEParameter);
        }
    
        public virtual ObjectResult<INSERTA_MODIFICACION_ESTADO_SOLICITUD_Result> INSERTA_MODIFICACION_ESTADO_SOLICITUD(Nullable<long> iDSOLICITUDPAGO, Nullable<long> iDMAESTROESTADOSOLICITUD, string uSUARIORESPONSABLEMODIFICACIONESTADOSOLICITUD)
        {
            var iDSOLICITUDPAGOParameter = iDSOLICITUDPAGO.HasValue ?
                new ObjectParameter("IDSOLICITUDPAGO", iDSOLICITUDPAGO) :
                new ObjectParameter("IDSOLICITUDPAGO", typeof(long));
    
            var iDMAESTROESTADOSOLICITUDParameter = iDMAESTROESTADOSOLICITUD.HasValue ?
                new ObjectParameter("IDMAESTROESTADOSOLICITUD", iDMAESTROESTADOSOLICITUD) :
                new ObjectParameter("IDMAESTROESTADOSOLICITUD", typeof(long));
    
            var uSUARIORESPONSABLEMODIFICACIONESTADOSOLICITUDParameter = uSUARIORESPONSABLEMODIFICACIONESTADOSOLICITUD != null ?
                new ObjectParameter("USUARIORESPONSABLEMODIFICACIONESTADOSOLICITUD", uSUARIORESPONSABLEMODIFICACIONESTADOSOLICITUD) :
                new ObjectParameter("USUARIORESPONSABLEMODIFICACIONESTADOSOLICITUD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<INSERTA_MODIFICACION_ESTADO_SOLICITUD_Result>("INSERTA_MODIFICACION_ESTADO_SOLICITUD", iDSOLICITUDPAGOParameter, iDMAESTROESTADOSOLICITUDParameter, uSUARIORESPONSABLEMODIFICACIONESTADOSOLICITUDParameter);
        }
    
        public virtual ObjectResult<INSERTA_PRESUPUESTO_REGIONAL_IGTD_Result> INSERTA_PRESUPUESTO_REGIONAL_IGTD(Nullable<short> aNNORESOLUCION, Nullable<int> nUMERORESOLUCION, Nullable<System.DateTime> fECHARESOLUCION, Nullable<int> cODIGOREGION, Nullable<long> mONTOPRESUPUESTOREGIONAL, string oBSERVACION, string nOMBREARCHIVO, string uSUARIO)
        {
            var aNNORESOLUCIONParameter = aNNORESOLUCION.HasValue ?
                new ObjectParameter("ANNORESOLUCION", aNNORESOLUCION) :
                new ObjectParameter("ANNORESOLUCION", typeof(short));
    
            var nUMERORESOLUCIONParameter = nUMERORESOLUCION.HasValue ?
                new ObjectParameter("NUMERORESOLUCION", nUMERORESOLUCION) :
                new ObjectParameter("NUMERORESOLUCION", typeof(int));
    
            var fECHARESOLUCIONParameter = fECHARESOLUCION.HasValue ?
                new ObjectParameter("FECHARESOLUCION", fECHARESOLUCION) :
                new ObjectParameter("FECHARESOLUCION", typeof(System.DateTime));
    
            var cODIGOREGIONParameter = cODIGOREGION.HasValue ?
                new ObjectParameter("CODIGOREGION", cODIGOREGION) :
                new ObjectParameter("CODIGOREGION", typeof(int));
    
            var mONTOPRESUPUESTOREGIONALParameter = mONTOPRESUPUESTOREGIONAL.HasValue ?
                new ObjectParameter("MONTOPRESUPUESTOREGIONAL", mONTOPRESUPUESTOREGIONAL) :
                new ObjectParameter("MONTOPRESUPUESTOREGIONAL", typeof(long));
    
            var oBSERVACIONParameter = oBSERVACION != null ?
                new ObjectParameter("OBSERVACION", oBSERVACION) :
                new ObjectParameter("OBSERVACION", typeof(string));
    
            var nOMBREARCHIVOParameter = nOMBREARCHIVO != null ?
                new ObjectParameter("NOMBREARCHIVO", nOMBREARCHIVO) :
                new ObjectParameter("NOMBREARCHIVO", typeof(string));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<INSERTA_PRESUPUESTO_REGIONAL_IGTD_Result>("INSERTA_PRESUPUESTO_REGIONAL_IGTD", aNNORESOLUCIONParameter, nUMERORESOLUCIONParameter, fECHARESOLUCIONParameter, cODIGOREGIONParameter, mONTOPRESUPUESTOREGIONALParameter, oBSERVACIONParameter, nOMBREARCHIVOParameter, uSUARIOParameter);
        }
    
        public virtual ObjectResult<SNAT_SIMPLIFICADO_V_UPD_AUTORIZACION_ORDEN_PAGO_SIMP_Result> SNAT_SIMPLIFICADO_V_UPD_AUTORIZACION_ORDEN_PAGO_SIMP(string oRD_PAG_NUM_DOC, string uSER, Nullable<int> indicaATPrevia, string comentario)
        {
            var oRD_PAG_NUM_DOCParameter = oRD_PAG_NUM_DOC != null ?
                new ObjectParameter("ORD_PAG_NUM_DOC", oRD_PAG_NUM_DOC) :
                new ObjectParameter("ORD_PAG_NUM_DOC", typeof(string));
    
            var uSERParameter = uSER != null ?
                new ObjectParameter("USER", uSER) :
                new ObjectParameter("USER", typeof(string));
    
            var indicaATPreviaParameter = indicaATPrevia.HasValue ?
                new ObjectParameter("IndicaATPrevia", indicaATPrevia) :
                new ObjectParameter("IndicaATPrevia", typeof(int));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("Comentario", comentario) :
                new ObjectParameter("Comentario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SNAT_SIMPLIFICADO_V_UPD_AUTORIZACION_ORDEN_PAGO_SIMP_Result>("SNAT_SIMPLIFICADO_V_UPD_AUTORIZACION_ORDEN_PAGO_SIMP", oRD_PAG_NUM_DOCParameter, uSERParameter, indicaATPreviaParameter, comentarioParameter);
        }
    
        public virtual ObjectResult<SNAT_SIMPLIFICADO_V_UPD_REPARO_ORDEN_PAGO_SIMP_Result> SNAT_SIMPLIFICADO_V_UPD_REPARO_ORDEN_PAGO_SIMP(string oRD_PAG_NUM_DOC, string uSER, Nullable<int> indicaATPrevia, string comentario)
        {
            var oRD_PAG_NUM_DOCParameter = oRD_PAG_NUM_DOC != null ?
                new ObjectParameter("ORD_PAG_NUM_DOC", oRD_PAG_NUM_DOC) :
                new ObjectParameter("ORD_PAG_NUM_DOC", typeof(string));
    
            var uSERParameter = uSER != null ?
                new ObjectParameter("USER", uSER) :
                new ObjectParameter("USER", typeof(string));
    
            var indicaATPreviaParameter = indicaATPrevia.HasValue ?
                new ObjectParameter("IndicaATPrevia", indicaATPrevia) :
                new ObjectParameter("IndicaATPrevia", typeof(int));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("Comentario", comentario) :
                new ObjectParameter("Comentario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SNAT_SIMPLIFICADO_V_UPD_REPARO_ORDEN_PAGO_SIMP_Result>("SNAT_SIMPLIFICADO_V_UPD_REPARO_ORDEN_PAGO_SIMP", oRD_PAG_NUM_DOCParameter, uSERParameter, indicaATPreviaParameter, comentarioParameter);
        }
    
        public virtual ObjectResult<SNAT_SIMPLIFICADO_V_USP_CON_LISTADO_AUTORIZACION_Result> SNAT_SIMPLIFICADO_V_USP_CON_LISTADO_AUTORIZACION(string pCODIGOPROYECTO, Nullable<long> pIDPROGRAMA, Nullable<long> pIDTIPOLOGIA, Nullable<long> pIDLLAMADO, Nullable<long> pIDTIPOPROVEEDOR, string pNOMBREPROVEEDOR, Nullable<long> pIDSERVICIO, Nullable<long> pREGION, Nullable<long> pPROVINCIA, Nullable<long> pCOMUNA, Nullable<long> pIDMODALIDAD, Nullable<long> pIDAUTORIZACION, Nullable<long> pIDMAESTROTITULO, Nullable<long> pIDMAESTROESTADOAUTORIZACION)
        {
            var pCODIGOPROYECTOParameter = pCODIGOPROYECTO != null ?
                new ObjectParameter("pCODIGOPROYECTO", pCODIGOPROYECTO) :
                new ObjectParameter("pCODIGOPROYECTO", typeof(string));
    
            var pIDPROGRAMAParameter = pIDPROGRAMA.HasValue ?
                new ObjectParameter("pIDPROGRAMA", pIDPROGRAMA) :
                new ObjectParameter("pIDPROGRAMA", typeof(long));
    
            var pIDTIPOLOGIAParameter = pIDTIPOLOGIA.HasValue ?
                new ObjectParameter("pIDTIPOLOGIA", pIDTIPOLOGIA) :
                new ObjectParameter("pIDTIPOLOGIA", typeof(long));
    
            var pIDLLAMADOParameter = pIDLLAMADO.HasValue ?
                new ObjectParameter("pIDLLAMADO", pIDLLAMADO) :
                new ObjectParameter("pIDLLAMADO", typeof(long));
    
            var pIDTIPOPROVEEDORParameter = pIDTIPOPROVEEDOR.HasValue ?
                new ObjectParameter("pIDTIPOPROVEEDOR", pIDTIPOPROVEEDOR) :
                new ObjectParameter("pIDTIPOPROVEEDOR", typeof(long));
    
            var pNOMBREPROVEEDORParameter = pNOMBREPROVEEDOR != null ?
                new ObjectParameter("pNOMBREPROVEEDOR", pNOMBREPROVEEDOR) :
                new ObjectParameter("pNOMBREPROVEEDOR", typeof(string));
    
            var pIDSERVICIOParameter = pIDSERVICIO.HasValue ?
                new ObjectParameter("pIDSERVICIO", pIDSERVICIO) :
                new ObjectParameter("pIDSERVICIO", typeof(long));
    
            var pREGIONParameter = pREGION.HasValue ?
                new ObjectParameter("pREGION", pREGION) :
                new ObjectParameter("pREGION", typeof(long));
    
            var pPROVINCIAParameter = pPROVINCIA.HasValue ?
                new ObjectParameter("pPROVINCIA", pPROVINCIA) :
                new ObjectParameter("pPROVINCIA", typeof(long));
    
            var pCOMUNAParameter = pCOMUNA.HasValue ?
                new ObjectParameter("pCOMUNA", pCOMUNA) :
                new ObjectParameter("pCOMUNA", typeof(long));
    
            var pIDMODALIDADParameter = pIDMODALIDAD.HasValue ?
                new ObjectParameter("pIDMODALIDAD", pIDMODALIDAD) :
                new ObjectParameter("pIDMODALIDAD", typeof(long));
    
            var pIDAUTORIZACIONParameter = pIDAUTORIZACION.HasValue ?
                new ObjectParameter("pIDAUTORIZACION", pIDAUTORIZACION) :
                new ObjectParameter("pIDAUTORIZACION", typeof(long));
    
            var pIDMAESTROTITULOParameter = pIDMAESTROTITULO.HasValue ?
                new ObjectParameter("pIDMAESTROTITULO", pIDMAESTROTITULO) :
                new ObjectParameter("pIDMAESTROTITULO", typeof(long));
    
            var pIDMAESTROESTADOAUTORIZACIONParameter = pIDMAESTROESTADOAUTORIZACION.HasValue ?
                new ObjectParameter("pIDMAESTROESTADOAUTORIZACION", pIDMAESTROESTADOAUTORIZACION) :
                new ObjectParameter("pIDMAESTROESTADOAUTORIZACION", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SNAT_SIMPLIFICADO_V_USP_CON_LISTADO_AUTORIZACION_Result>("SNAT_SIMPLIFICADO_V_USP_CON_LISTADO_AUTORIZACION", pCODIGOPROYECTOParameter, pIDPROGRAMAParameter, pIDTIPOLOGIAParameter, pIDLLAMADOParameter, pIDTIPOPROVEEDORParameter, pNOMBREPROVEEDORParameter, pIDSERVICIOParameter, pREGIONParameter, pPROVINCIAParameter, pCOMUNAParameter, pIDMODALIDADParameter, pIDAUTORIZACIONParameter, pIDMAESTROTITULOParameter, pIDMAESTROESTADOAUTORIZACIONParameter);
        }
    
        public virtual ObjectResult<SNAT_SIMPLIFICADO_V_USP_CON_LISTADO_SOLICITUDES_PAGO_Result> SNAT_SIMPLIFICADO_V_USP_CON_LISTADO_SOLICITUDES_PAGO(string pCODIGOPROYECTO, Nullable<long> pIDPROGRAMA, Nullable<long> pIDTIPOLOGIA, Nullable<long> pIDLLAMADO, Nullable<long> pIDTIPOPROVEEDOR, string pNOMBREPROVEEDOR, string pNOMBRESERVICIO, Nullable<long> pREGION, Nullable<long> pPROVINCIA, Nullable<long> pCOMUNA, Nullable<long> pIDMODALIDAD, Nullable<long> pIDAUTORIZACION)
        {
            var pCODIGOPROYECTOParameter = pCODIGOPROYECTO != null ?
                new ObjectParameter("pCODIGOPROYECTO", pCODIGOPROYECTO) :
                new ObjectParameter("pCODIGOPROYECTO", typeof(string));
    
            var pIDPROGRAMAParameter = pIDPROGRAMA.HasValue ?
                new ObjectParameter("pIDPROGRAMA", pIDPROGRAMA) :
                new ObjectParameter("pIDPROGRAMA", typeof(long));
    
            var pIDTIPOLOGIAParameter = pIDTIPOLOGIA.HasValue ?
                new ObjectParameter("pIDTIPOLOGIA", pIDTIPOLOGIA) :
                new ObjectParameter("pIDTIPOLOGIA", typeof(long));
    
            var pIDLLAMADOParameter = pIDLLAMADO.HasValue ?
                new ObjectParameter("pIDLLAMADO", pIDLLAMADO) :
                new ObjectParameter("pIDLLAMADO", typeof(long));
    
            var pIDTIPOPROVEEDORParameter = pIDTIPOPROVEEDOR.HasValue ?
                new ObjectParameter("pIDTIPOPROVEEDOR", pIDTIPOPROVEEDOR) :
                new ObjectParameter("pIDTIPOPROVEEDOR", typeof(long));
    
            var pNOMBREPROVEEDORParameter = pNOMBREPROVEEDOR != null ?
                new ObjectParameter("pNOMBREPROVEEDOR", pNOMBREPROVEEDOR) :
                new ObjectParameter("pNOMBREPROVEEDOR", typeof(string));
    
            var pNOMBRESERVICIOParameter = pNOMBRESERVICIO != null ?
                new ObjectParameter("pNOMBRESERVICIO", pNOMBRESERVICIO) :
                new ObjectParameter("pNOMBRESERVICIO", typeof(string));
    
            var pREGIONParameter = pREGION.HasValue ?
                new ObjectParameter("pREGION", pREGION) :
                new ObjectParameter("pREGION", typeof(long));
    
            var pPROVINCIAParameter = pPROVINCIA.HasValue ?
                new ObjectParameter("pPROVINCIA", pPROVINCIA) :
                new ObjectParameter("pPROVINCIA", typeof(long));
    
            var pCOMUNAParameter = pCOMUNA.HasValue ?
                new ObjectParameter("pCOMUNA", pCOMUNA) :
                new ObjectParameter("pCOMUNA", typeof(long));
    
            var pIDMODALIDADParameter = pIDMODALIDAD.HasValue ?
                new ObjectParameter("pIDMODALIDAD", pIDMODALIDAD) :
                new ObjectParameter("pIDMODALIDAD", typeof(long));
    
            var pIDAUTORIZACIONParameter = pIDAUTORIZACION.HasValue ?
                new ObjectParameter("pIDAUTORIZACION", pIDAUTORIZACION) :
                new ObjectParameter("pIDAUTORIZACION", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SNAT_SIMPLIFICADO_V_USP_CON_LISTADO_SOLICITUDES_PAGO_Result>("SNAT_SIMPLIFICADO_V_USP_CON_LISTADO_SOLICITUDES_PAGO", pCODIGOPROYECTOParameter, pIDPROGRAMAParameter, pIDTIPOLOGIAParameter, pIDLLAMADOParameter, pIDTIPOPROVEEDORParameter, pNOMBREPROVEEDORParameter, pNOMBRESERVICIOParameter, pREGIONParameter, pPROVINCIAParameter, pCOMUNAParameter, pIDMODALIDADParameter, pIDAUTORIZACIONParameter);
        }
    
        public virtual ObjectResult<CONSULTA_CONTRATO_Result> CONSULTA_CONTRATO(Nullable<int> iDCONTRATO)
        {
            var iDCONTRATOParameter = iDCONTRATO.HasValue ?
                new ObjectParameter("IDCONTRATO", iDCONTRATO) :
                new ObjectParameter("IDCONTRATO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULTA_CONTRATO_Result>("CONSULTA_CONTRATO", iDCONTRATOParameter);
        }
    
        public virtual ObjectResult<CONSULTA_LISTADO_CONTRATO_Result> CONSULTA_LISTADO_CONTRATO(Nullable<int> aCCION, Nullable<int> aNNOPRESUPUESTO, Nullable<int> cODIGOREGION, Nullable<long> tIPOSERVICIO)
        {
            var aCCIONParameter = aCCION.HasValue ?
                new ObjectParameter("ACCION", aCCION) :
                new ObjectParameter("ACCION", typeof(int));
    
            var aNNOPRESUPUESTOParameter = aNNOPRESUPUESTO.HasValue ?
                new ObjectParameter("ANNOPRESUPUESTO", aNNOPRESUPUESTO) :
                new ObjectParameter("ANNOPRESUPUESTO", typeof(int));
    
            var cODIGOREGIONParameter = cODIGOREGION.HasValue ?
                new ObjectParameter("CODIGOREGION", cODIGOREGION) :
                new ObjectParameter("CODIGOREGION", typeof(int));
    
            var tIPOSERVICIOParameter = tIPOSERVICIO.HasValue ?
                new ObjectParameter("TIPOSERVICIO", tIPOSERVICIO) :
                new ObjectParameter("TIPOSERVICIO", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULTA_LISTADO_CONTRATO_Result>("CONSULTA_LISTADO_CONTRATO", aCCIONParameter, aNNOPRESUPUESTOParameter, cODIGOREGIONParameter, tIPOSERVICIOParameter);
        }
    
        public virtual ObjectResult<SNAT_SIMPLIFICADO_V_CONSULTA_ANO_CONTRATO_ATP_Result> SNAT_SIMPLIFICADO_V_CONSULTA_ANO_CONTRATO_ATP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SNAT_SIMPLIFICADO_V_CONSULTA_ANO_CONTRATO_ATP_Result>("SNAT_SIMPLIFICADO_V_CONSULTA_ANO_CONTRATO_ATP");
        }
    
        public virtual ObjectResult<SNAT_SIMPLIFICADO_V_CONSULTA_SERVICIOS_SOLICITUD_ATP_Result> SNAT_SIMPLIFICADO_V_CONSULTA_SERVICIOS_SOLICITUD_ATP(Nullable<long> nIdSolicitudPago, string nRegion, string nResolucionContrato, string nFechaResolucionContrato, string nMontoContrato, string nRutProveedor, string nMontoAutorizacionPago, string nFechaDevengo)
        {
            var nIdSolicitudPagoParameter = nIdSolicitudPago.HasValue ?
                new ObjectParameter("nIdSolicitudPago", nIdSolicitudPago) :
                new ObjectParameter("nIdSolicitudPago", typeof(long));
    
            var nRegionParameter = nRegion != null ?
                new ObjectParameter("nRegion", nRegion) :
                new ObjectParameter("nRegion", typeof(string));
    
            var nResolucionContratoParameter = nResolucionContrato != null ?
                new ObjectParameter("nResolucionContrato", nResolucionContrato) :
                new ObjectParameter("nResolucionContrato", typeof(string));
    
            var nFechaResolucionContratoParameter = nFechaResolucionContrato != null ?
                new ObjectParameter("nFechaResolucionContrato", nFechaResolucionContrato) :
                new ObjectParameter("nFechaResolucionContrato", typeof(string));
    
            var nMontoContratoParameter = nMontoContrato != null ?
                new ObjectParameter("nMontoContrato", nMontoContrato) :
                new ObjectParameter("nMontoContrato", typeof(string));
    
            var nRutProveedorParameter = nRutProveedor != null ?
                new ObjectParameter("nRutProveedor", nRutProveedor) :
                new ObjectParameter("nRutProveedor", typeof(string));
    
            var nMontoAutorizacionPagoParameter = nMontoAutorizacionPago != null ?
                new ObjectParameter("nMontoAutorizacionPago", nMontoAutorizacionPago) :
                new ObjectParameter("nMontoAutorizacionPago", typeof(string));
    
            var nFechaDevengoParameter = nFechaDevengo != null ?
                new ObjectParameter("nFechaDevengo", nFechaDevengo) :
                new ObjectParameter("nFechaDevengo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SNAT_SIMPLIFICADO_V_CONSULTA_SERVICIOS_SOLICITUD_ATP_Result>("SNAT_SIMPLIFICADO_V_CONSULTA_SERVICIOS_SOLICITUD_ATP", nIdSolicitudPagoParameter, nRegionParameter, nResolucionContratoParameter, nFechaResolucionContratoParameter, nMontoContratoParameter, nRutProveedorParameter, nMontoAutorizacionPagoParameter, nFechaDevengoParameter);
        }
    
        public virtual ObjectResult<CONSULTA_LISTADO_SOLICITUD_Result> CONSULTA_LISTADO_SOLICITUD(Nullable<int> aCCION, Nullable<long> nUMERORESOLUCION, Nullable<int> cODIGOREGION, Nullable<int> aNNOPRESUPUESTO)
        {
            var aCCIONParameter = aCCION.HasValue ?
                new ObjectParameter("ACCION", aCCION) :
                new ObjectParameter("ACCION", typeof(int));
    
            var nUMERORESOLUCIONParameter = nUMERORESOLUCION.HasValue ?
                new ObjectParameter("NUMERORESOLUCION", nUMERORESOLUCION) :
                new ObjectParameter("NUMERORESOLUCION", typeof(long));
    
            var cODIGOREGIONParameter = cODIGOREGION.HasValue ?
                new ObjectParameter("CODIGOREGION", cODIGOREGION) :
                new ObjectParameter("CODIGOREGION", typeof(int));
    
            var aNNOPRESUPUESTOParameter = aNNOPRESUPUESTO.HasValue ?
                new ObjectParameter("ANNOPRESUPUESTO", aNNOPRESUPUESTO) :
                new ObjectParameter("ANNOPRESUPUESTO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULTA_LISTADO_SOLICITUD_Result>("CONSULTA_LISTADO_SOLICITUD", aCCIONParameter, nUMERORESOLUCIONParameter, cODIGOREGIONParameter, aNNOPRESUPUESTOParameter);
        }
    
        public virtual ObjectResult<CONSULTA_PRESUPUESTO_REGIONAL_IGTD_Result> CONSULTA_PRESUPUESTO_REGIONAL_IGTD(Nullable<int> aCCION, Nullable<int> cONSULTA_PRESUPUESTO_NUMERO, Nullable<int> cONSULTA_PRESUPUESTO_ANNO, Nullable<int> cONSULTA_PRESUPUESTO_REGION)
        {
            var aCCIONParameter = aCCION.HasValue ?
                new ObjectParameter("ACCION", aCCION) :
                new ObjectParameter("ACCION", typeof(int));
    
            var cONSULTA_PRESUPUESTO_NUMEROParameter = cONSULTA_PRESUPUESTO_NUMERO.HasValue ?
                new ObjectParameter("CONSULTA_PRESUPUESTO_NUMERO", cONSULTA_PRESUPUESTO_NUMERO) :
                new ObjectParameter("CONSULTA_PRESUPUESTO_NUMERO", typeof(int));
    
            var cONSULTA_PRESUPUESTO_ANNOParameter = cONSULTA_PRESUPUESTO_ANNO.HasValue ?
                new ObjectParameter("CONSULTA_PRESUPUESTO_ANNO", cONSULTA_PRESUPUESTO_ANNO) :
                new ObjectParameter("CONSULTA_PRESUPUESTO_ANNO", typeof(int));
    
            var cONSULTA_PRESUPUESTO_REGIONParameter = cONSULTA_PRESUPUESTO_REGION.HasValue ?
                new ObjectParameter("CONSULTA_PRESUPUESTO_REGION", cONSULTA_PRESUPUESTO_REGION) :
                new ObjectParameter("CONSULTA_PRESUPUESTO_REGION", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULTA_PRESUPUESTO_REGIONAL_IGTD_Result>("CONSULTA_PRESUPUESTO_REGIONAL_IGTD", aCCIONParameter, cONSULTA_PRESUPUESTO_NUMEROParameter, cONSULTA_PRESUPUESTO_ANNOParameter, cONSULTA_PRESUPUESTO_REGIONParameter);
        }
    
        public virtual ObjectResult<CABECERA_AUTORIZACION_PAGO_Result> CABECERA_AUTORIZACION_PAGO(Nullable<long> iDAUTORIZACION)
        {
            var iDAUTORIZACIONParameter = iDAUTORIZACION.HasValue ?
                new ObjectParameter("IDAUTORIZACION", iDAUTORIZACION) :
                new ObjectParameter("IDAUTORIZACION", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CABECERA_AUTORIZACION_PAGO_Result>("CABECERA_AUTORIZACION_PAGO", iDAUTORIZACIONParameter);
        }
    
        public virtual ObjectResult<BUSQUEDA_DETALLE_AUTORIZACION_DE_PAGO_GRILLA_PDF_Result> BUSQUEDA_DETALLE_AUTORIZACION_DE_PAGO_GRILLA_PDF(Nullable<long> iDAUTORIZACION)
        {
            var iDAUTORIZACIONParameter = iDAUTORIZACION.HasValue ?
                new ObjectParameter("IDAUTORIZACION", iDAUTORIZACION) :
                new ObjectParameter("IDAUTORIZACION", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BUSQUEDA_DETALLE_AUTORIZACION_DE_PAGO_GRILLA_PDF_Result>("BUSQUEDA_DETALLE_AUTORIZACION_DE_PAGO_GRILLA_PDF", iDAUTORIZACIONParameter);
        }
    
        public virtual ObjectResult<BUSQUEDA_DETALLE_AUTORIZACION_DE_PAGO_Result> BUSQUEDA_DETALLE_AUTORIZACION_DE_PAGO(Nullable<long> iDAUTORIZACION)
        {
            var iDAUTORIZACIONParameter = iDAUTORIZACION.HasValue ?
                new ObjectParameter("IDAUTORIZACION", iDAUTORIZACION) :
                new ObjectParameter("IDAUTORIZACION", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BUSQUEDA_DETALLE_AUTORIZACION_DE_PAGO_Result>("BUSQUEDA_DETALLE_AUTORIZACION_DE_PAGO", iDAUTORIZACIONParameter);
        }
    
        public virtual ObjectResult<INSERTA_GENERACION_SOLICITUD_PAGO_Result> INSERTA_GENERACION_SOLICITUD_PAGO(Nullable<long> iDMAESTROESTADOSOLICITUD, string fOLIOBOLETAGARANTIASOLICITUDPAGO, Nullable<int> nUMEROFAMILIASPAGARSOLICITUDPAGO, string uSUARIORESPONSABLESOLICITUDPAGO, Nullable<long> iDCARACTERISTICASESPECIALES, Nullable<long> iDMAESTROTIPOPAGO, Nullable<System.DateTime> fECHAREALCREACIONSOLICITUDPAGO, Nullable<System.DateTime> fECHACREACIONSOLICITUDPAGO, Nullable<long> iDMAESTROTIPODESTINOPAGO, Nullable<decimal> mONTOTOTALPROYECTOSOLICITUDPAGO, Nullable<decimal> mONTOPAGADOSOLICITUDPAGO, Nullable<decimal> mONTOCOMPROMETIDOSOLICITUDPAGO, Nullable<decimal> sALDOPORPAGARSOLICITUDPAGO, Nullable<long> nUMERORESOLUCIONCONTRATOSOLICITUDPAGO, Nullable<decimal> mONTOSOLICITUDSOLICITUDPAGO, Nullable<long> iDPROVEEDOR, Nullable<int> nUMEROVIVIENDASSOLICITUDPAGO, string oBSERVACIONESSOLICITUDPAGO, Nullable<long> iDMAESTROTIPOPROVEEDOR, string nOMBREPROVEEDOR, Nullable<int> rUTPROVEEDOR, string dVPROVEDIGITOVERIFICADORPROVEEDOR, Nullable<decimal> aVANCEOBRAMUNIN, string eSTADOAVANCEOBRA, Nullable<System.DateTime> fECHARESOLUCIONSOLICITUDPAGO, Nullable<System.DateTime> fECHABOLETAGARANTIA, Nullable<long> iDPROVEEDORMANDATO)
        {
            var iDMAESTROESTADOSOLICITUDParameter = iDMAESTROESTADOSOLICITUD.HasValue ?
                new ObjectParameter("IDMAESTROESTADOSOLICITUD", iDMAESTROESTADOSOLICITUD) :
                new ObjectParameter("IDMAESTROESTADOSOLICITUD", typeof(long));
    
            var fOLIOBOLETAGARANTIASOLICITUDPAGOParameter = fOLIOBOLETAGARANTIASOLICITUDPAGO != null ?
                new ObjectParameter("FOLIOBOLETAGARANTIASOLICITUDPAGO", fOLIOBOLETAGARANTIASOLICITUDPAGO) :
                new ObjectParameter("FOLIOBOLETAGARANTIASOLICITUDPAGO", typeof(string));
    
            var nUMEROFAMILIASPAGARSOLICITUDPAGOParameter = nUMEROFAMILIASPAGARSOLICITUDPAGO.HasValue ?
                new ObjectParameter("NUMEROFAMILIASPAGARSOLICITUDPAGO", nUMEROFAMILIASPAGARSOLICITUDPAGO) :
                new ObjectParameter("NUMEROFAMILIASPAGARSOLICITUDPAGO", typeof(int));
    
            var uSUARIORESPONSABLESOLICITUDPAGOParameter = uSUARIORESPONSABLESOLICITUDPAGO != null ?
                new ObjectParameter("USUARIORESPONSABLESOLICITUDPAGO", uSUARIORESPONSABLESOLICITUDPAGO) :
                new ObjectParameter("USUARIORESPONSABLESOLICITUDPAGO", typeof(string));
    
            var iDCARACTERISTICASESPECIALESParameter = iDCARACTERISTICASESPECIALES.HasValue ?
                new ObjectParameter("IDCARACTERISTICASESPECIALES", iDCARACTERISTICASESPECIALES) :
                new ObjectParameter("IDCARACTERISTICASESPECIALES", typeof(long));
    
            var iDMAESTROTIPOPAGOParameter = iDMAESTROTIPOPAGO.HasValue ?
                new ObjectParameter("IDMAESTROTIPOPAGO", iDMAESTROTIPOPAGO) :
                new ObjectParameter("IDMAESTROTIPOPAGO", typeof(long));
    
            var fECHAREALCREACIONSOLICITUDPAGOParameter = fECHAREALCREACIONSOLICITUDPAGO.HasValue ?
                new ObjectParameter("FECHAREALCREACIONSOLICITUDPAGO", fECHAREALCREACIONSOLICITUDPAGO) :
                new ObjectParameter("FECHAREALCREACIONSOLICITUDPAGO", typeof(System.DateTime));
    
            var fECHACREACIONSOLICITUDPAGOParameter = fECHACREACIONSOLICITUDPAGO.HasValue ?
                new ObjectParameter("FECHACREACIONSOLICITUDPAGO", fECHACREACIONSOLICITUDPAGO) :
                new ObjectParameter("FECHACREACIONSOLICITUDPAGO", typeof(System.DateTime));
    
            var iDMAESTROTIPODESTINOPAGOParameter = iDMAESTROTIPODESTINOPAGO.HasValue ?
                new ObjectParameter("IDMAESTROTIPODESTINOPAGO", iDMAESTROTIPODESTINOPAGO) :
                new ObjectParameter("IDMAESTROTIPODESTINOPAGO", typeof(long));
    
            var mONTOTOTALPROYECTOSOLICITUDPAGOParameter = mONTOTOTALPROYECTOSOLICITUDPAGO.HasValue ?
                new ObjectParameter("MONTOTOTALPROYECTOSOLICITUDPAGO", mONTOTOTALPROYECTOSOLICITUDPAGO) :
                new ObjectParameter("MONTOTOTALPROYECTOSOLICITUDPAGO", typeof(decimal));
    
            var mONTOPAGADOSOLICITUDPAGOParameter = mONTOPAGADOSOLICITUDPAGO.HasValue ?
                new ObjectParameter("MONTOPAGADOSOLICITUDPAGO", mONTOPAGADOSOLICITUDPAGO) :
                new ObjectParameter("MONTOPAGADOSOLICITUDPAGO", typeof(decimal));
    
            var mONTOCOMPROMETIDOSOLICITUDPAGOParameter = mONTOCOMPROMETIDOSOLICITUDPAGO.HasValue ?
                new ObjectParameter("MONTOCOMPROMETIDOSOLICITUDPAGO", mONTOCOMPROMETIDOSOLICITUDPAGO) :
                new ObjectParameter("MONTOCOMPROMETIDOSOLICITUDPAGO", typeof(decimal));
    
            var sALDOPORPAGARSOLICITUDPAGOParameter = sALDOPORPAGARSOLICITUDPAGO.HasValue ?
                new ObjectParameter("SALDOPORPAGARSOLICITUDPAGO", sALDOPORPAGARSOLICITUDPAGO) :
                new ObjectParameter("SALDOPORPAGARSOLICITUDPAGO", typeof(decimal));
    
            var nUMERORESOLUCIONCONTRATOSOLICITUDPAGOParameter = nUMERORESOLUCIONCONTRATOSOLICITUDPAGO.HasValue ?
                new ObjectParameter("NUMERORESOLUCIONCONTRATOSOLICITUDPAGO", nUMERORESOLUCIONCONTRATOSOLICITUDPAGO) :
                new ObjectParameter("NUMERORESOLUCIONCONTRATOSOLICITUDPAGO", typeof(long));
    
            var mONTOSOLICITUDSOLICITUDPAGOParameter = mONTOSOLICITUDSOLICITUDPAGO.HasValue ?
                new ObjectParameter("MONTOSOLICITUDSOLICITUDPAGO", mONTOSOLICITUDSOLICITUDPAGO) :
                new ObjectParameter("MONTOSOLICITUDSOLICITUDPAGO", typeof(decimal));
    
            var iDPROVEEDORParameter = iDPROVEEDOR.HasValue ?
                new ObjectParameter("IDPROVEEDOR", iDPROVEEDOR) :
                new ObjectParameter("IDPROVEEDOR", typeof(long));
    
            var nUMEROVIVIENDASSOLICITUDPAGOParameter = nUMEROVIVIENDASSOLICITUDPAGO.HasValue ?
                new ObjectParameter("NUMEROVIVIENDASSOLICITUDPAGO", nUMEROVIVIENDASSOLICITUDPAGO) :
                new ObjectParameter("NUMEROVIVIENDASSOLICITUDPAGO", typeof(int));
    
            var oBSERVACIONESSOLICITUDPAGOParameter = oBSERVACIONESSOLICITUDPAGO != null ?
                new ObjectParameter("OBSERVACIONESSOLICITUDPAGO", oBSERVACIONESSOLICITUDPAGO) :
                new ObjectParameter("OBSERVACIONESSOLICITUDPAGO", typeof(string));
    
            var iDMAESTROTIPOPROVEEDORParameter = iDMAESTROTIPOPROVEEDOR.HasValue ?
                new ObjectParameter("IDMAESTROTIPOPROVEEDOR", iDMAESTROTIPOPROVEEDOR) :
                new ObjectParameter("IDMAESTROTIPOPROVEEDOR", typeof(long));
    
            var nOMBREPROVEEDORParameter = nOMBREPROVEEDOR != null ?
                new ObjectParameter("NOMBREPROVEEDOR", nOMBREPROVEEDOR) :
                new ObjectParameter("NOMBREPROVEEDOR", typeof(string));
    
            var rUTPROVEEDORParameter = rUTPROVEEDOR.HasValue ?
                new ObjectParameter("RUTPROVEEDOR", rUTPROVEEDOR) :
                new ObjectParameter("RUTPROVEEDOR", typeof(int));
    
            var dVPROVEDIGITOVERIFICADORPROVEEDORParameter = dVPROVEDIGITOVERIFICADORPROVEEDOR != null ?
                new ObjectParameter("DVPROVEDIGITOVERIFICADORPROVEEDOR", dVPROVEDIGITOVERIFICADORPROVEEDOR) :
                new ObjectParameter("DVPROVEDIGITOVERIFICADORPROVEEDOR", typeof(string));
    
            var aVANCEOBRAMUNINParameter = aVANCEOBRAMUNIN.HasValue ?
                new ObjectParameter("AVANCEOBRAMUNIN", aVANCEOBRAMUNIN) :
                new ObjectParameter("AVANCEOBRAMUNIN", typeof(decimal));
    
            var eSTADOAVANCEOBRAParameter = eSTADOAVANCEOBRA != null ?
                new ObjectParameter("ESTADOAVANCEOBRA", eSTADOAVANCEOBRA) :
                new ObjectParameter("ESTADOAVANCEOBRA", typeof(string));
    
            var fECHARESOLUCIONSOLICITUDPAGOParameter = fECHARESOLUCIONSOLICITUDPAGO.HasValue ?
                new ObjectParameter("FECHARESOLUCIONSOLICITUDPAGO", fECHARESOLUCIONSOLICITUDPAGO) :
                new ObjectParameter("FECHARESOLUCIONSOLICITUDPAGO", typeof(System.DateTime));
    
            var fECHABOLETAGARANTIAParameter = fECHABOLETAGARANTIA.HasValue ?
                new ObjectParameter("FECHABOLETAGARANTIA", fECHABOLETAGARANTIA) :
                new ObjectParameter("FECHABOLETAGARANTIA", typeof(System.DateTime));
    
            var iDPROVEEDORMANDATOParameter = iDPROVEEDORMANDATO.HasValue ?
                new ObjectParameter("IDPROVEEDORMANDATO", iDPROVEEDORMANDATO) :
                new ObjectParameter("IDPROVEEDORMANDATO", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<INSERTA_GENERACION_SOLICITUD_PAGO_Result>("INSERTA_GENERACION_SOLICITUD_PAGO", iDMAESTROESTADOSOLICITUDParameter, fOLIOBOLETAGARANTIASOLICITUDPAGOParameter, nUMEROFAMILIASPAGARSOLICITUDPAGOParameter, uSUARIORESPONSABLESOLICITUDPAGOParameter, iDCARACTERISTICASESPECIALESParameter, iDMAESTROTIPOPAGOParameter, fECHAREALCREACIONSOLICITUDPAGOParameter, fECHACREACIONSOLICITUDPAGOParameter, iDMAESTROTIPODESTINOPAGOParameter, mONTOTOTALPROYECTOSOLICITUDPAGOParameter, mONTOPAGADOSOLICITUDPAGOParameter, mONTOCOMPROMETIDOSOLICITUDPAGOParameter, sALDOPORPAGARSOLICITUDPAGOParameter, nUMERORESOLUCIONCONTRATOSOLICITUDPAGOParameter, mONTOSOLICITUDSOLICITUDPAGOParameter, iDPROVEEDORParameter, nUMEROVIVIENDASSOLICITUDPAGOParameter, oBSERVACIONESSOLICITUDPAGOParameter, iDMAESTROTIPOPROVEEDORParameter, nOMBREPROVEEDORParameter, rUTPROVEEDORParameter, dVPROVEDIGITOVERIFICADORPROVEEDORParameter, aVANCEOBRAMUNINParameter, eSTADOAVANCEOBRAParameter, fECHARESOLUCIONSOLICITUDPAGOParameter, fECHABOLETAGARANTIAParameter, iDPROVEEDORMANDATOParameter);
        }
    
        public virtual ObjectResult<INSERTA_SOLICITUD_ATP_Result> INSERTA_SOLICITUD_ATP(Nullable<long> iDSOLICITUDATP, Nullable<long> iDCONTRATO, Nullable<int> aNNOPRESUPUESTO, Nullable<long> mONTOPRESUPESTO, Nullable<int> cODIGOREGION, Nullable<long> mONTOPAGADO, Nullable<long> mONTOCOMPROMETIDO, Nullable<long> mONTOPORPAGAR, string aCTIVIDADES, Nullable<long> nUMEROBOLFACT, Nullable<System.DateTime> fECHABOLETAFACT, Nullable<long> mONTOTOTALAPAGAR, Nullable<bool> vBSERVICIO, string vBRESPONSABLE, Nullable<System.DateTime> vBFECHA, Nullable<long> eSTADOSOLICITUD, Nullable<long> iDMAESTROTIPOPAGO)
        {
            var iDSOLICITUDATPParameter = iDSOLICITUDATP.HasValue ?
                new ObjectParameter("IDSOLICITUDATP", iDSOLICITUDATP) :
                new ObjectParameter("IDSOLICITUDATP", typeof(long));
    
            var iDCONTRATOParameter = iDCONTRATO.HasValue ?
                new ObjectParameter("IDCONTRATO", iDCONTRATO) :
                new ObjectParameter("IDCONTRATO", typeof(long));
    
            var aNNOPRESUPUESTOParameter = aNNOPRESUPUESTO.HasValue ?
                new ObjectParameter("ANNOPRESUPUESTO", aNNOPRESUPUESTO) :
                new ObjectParameter("ANNOPRESUPUESTO", typeof(int));
    
            var mONTOPRESUPESTOParameter = mONTOPRESUPESTO.HasValue ?
                new ObjectParameter("MONTOPRESUPESTO", mONTOPRESUPESTO) :
                new ObjectParameter("MONTOPRESUPESTO", typeof(long));
    
            var cODIGOREGIONParameter = cODIGOREGION.HasValue ?
                new ObjectParameter("CODIGOREGION", cODIGOREGION) :
                new ObjectParameter("CODIGOREGION", typeof(int));
    
            var mONTOPAGADOParameter = mONTOPAGADO.HasValue ?
                new ObjectParameter("MONTOPAGADO", mONTOPAGADO) :
                new ObjectParameter("MONTOPAGADO", typeof(long));
    
            var mONTOCOMPROMETIDOParameter = mONTOCOMPROMETIDO.HasValue ?
                new ObjectParameter("MONTOCOMPROMETIDO", mONTOCOMPROMETIDO) :
                new ObjectParameter("MONTOCOMPROMETIDO", typeof(long));
    
            var mONTOPORPAGARParameter = mONTOPORPAGAR.HasValue ?
                new ObjectParameter("MONTOPORPAGAR", mONTOPORPAGAR) :
                new ObjectParameter("MONTOPORPAGAR", typeof(long));
    
            var aCTIVIDADESParameter = aCTIVIDADES != null ?
                new ObjectParameter("ACTIVIDADES", aCTIVIDADES) :
                new ObjectParameter("ACTIVIDADES", typeof(string));
    
            var nUMEROBOLFACTParameter = nUMEROBOLFACT.HasValue ?
                new ObjectParameter("NUMEROBOLFACT", nUMEROBOLFACT) :
                new ObjectParameter("NUMEROBOLFACT", typeof(long));
    
            var fECHABOLETAFACTParameter = fECHABOLETAFACT.HasValue ?
                new ObjectParameter("FECHABOLETAFACT", fECHABOLETAFACT) :
                new ObjectParameter("FECHABOLETAFACT", typeof(System.DateTime));
    
            var mONTOTOTALAPAGARParameter = mONTOTOTALAPAGAR.HasValue ?
                new ObjectParameter("MONTOTOTALAPAGAR", mONTOTOTALAPAGAR) :
                new ObjectParameter("MONTOTOTALAPAGAR", typeof(long));
    
            var vBSERVICIOParameter = vBSERVICIO.HasValue ?
                new ObjectParameter("VBSERVICIO", vBSERVICIO) :
                new ObjectParameter("VBSERVICIO", typeof(bool));
    
            var vBRESPONSABLEParameter = vBRESPONSABLE != null ?
                new ObjectParameter("VBRESPONSABLE", vBRESPONSABLE) :
                new ObjectParameter("VBRESPONSABLE", typeof(string));
    
            var vBFECHAParameter = vBFECHA.HasValue ?
                new ObjectParameter("VBFECHA", vBFECHA) :
                new ObjectParameter("VBFECHA", typeof(System.DateTime));
    
            var eSTADOSOLICITUDParameter = eSTADOSOLICITUD.HasValue ?
                new ObjectParameter("ESTADOSOLICITUD", eSTADOSOLICITUD) :
                new ObjectParameter("ESTADOSOLICITUD", typeof(long));
    
            var iDMAESTROTIPOPAGOParameter = iDMAESTROTIPOPAGO.HasValue ?
                new ObjectParameter("IDMAESTROTIPOPAGO", iDMAESTROTIPOPAGO) :
                new ObjectParameter("IDMAESTROTIPOPAGO", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<INSERTA_SOLICITUD_ATP_Result>("INSERTA_SOLICITUD_ATP", iDSOLICITUDATPParameter, iDCONTRATOParameter, aNNOPRESUPUESTOParameter, mONTOPRESUPESTOParameter, cODIGOREGIONParameter, mONTOPAGADOParameter, mONTOCOMPROMETIDOParameter, mONTOPORPAGARParameter, aCTIVIDADESParameter, nUMEROBOLFACTParameter, fECHABOLETAFACTParameter, mONTOTOTALAPAGARParameter, vBSERVICIOParameter, vBRESPONSABLEParameter, vBFECHAParameter, eSTADOSOLICITUDParameter, iDMAESTROTIPOPAGOParameter);
        }
    }
}
