//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIRECCION()
        {
            this.BENEFICIARIO = new HashSet<BENEFICIARIO>();
            this.INFORMACION_PROYECTO_SOLICITUD = new HashSet<INFORMACION_PROYECTO_SOLICITUD>();
            this.INFORMACION_PROYECTO = new HashSet<INFORMACION_PROYECTO>();
        }
    
        public long IDDIRECCION { get; set; }
        public string NUMERODIRECCION { get; set; }
        public Nullable<int> CODIGOCOMUNADIRECCION { get; set; }
        public Nullable<int> CODIGOPROVINCIADIRECCION { get; set; }
        public Nullable<int> CODIGOREGIONDIRECCION { get; set; }
        public string DESCRIPCIONDIRECCION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BENEFICIARIO> BENEFICIARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFORMACION_PROYECTO_SOLICITUD> INFORMACION_PROYECTO_SOLICITUD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFORMACION_PROYECTO> INFORMACION_PROYECTO { get; set; }
    }
}
