//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOMOLOGACION_INFORMACION_SISTEMA
    {
        public long IDHOMOLOGACIONINFORMACIONSISTEMA { get; set; }
        public long IDMAESTROINFORMACIONSISTEMAEXTERNO { get; set; }
        public string CODIGOSISTEMAINTERNOHOMOLOGACIONINFORMACIONSISTEMA { get; set; }
        public string NOMBRETABLAHOMOLOGACIONINFORMACIONSISTEMA { get; set; }
        public string COLUMNACODIGOTABLAHOMOLOGACIONINFORMACIONSISTEMA { get; set; }
        public string COLUMNADETALLETABLAHOMOLOGACIONINFORMACIONSISTEMA { get; set; }
    
        public virtual MAESTRO_INFORMACION_SISTEMA_EXTERNO MAESTRO_INFORMACION_SISTEMA_EXTERNO { get; set; }
    }
}
