//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORMACION_PROYECTO_SOLICITUD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFORMACION_PROYECTO_SOLICITUD()
        {
            this.SOLICITUD_PAGO = new HashSet<SOLICITUD_PAGO>();
        }
    
        public long IDINFORMACIONPROYECTOSOLICITUD { get; set; }
        public long IDINFORMACIONPROYECTO { get; set; }
        public Nullable<long> IDMAESTROPROGRAMA { get; set; }
        public Nullable<long> IDMAESTROLLAMADO { get; set; }
        public Nullable<long> IDMAESTROMODALIDAD { get; set; }
        public Nullable<long> IDMAESTROTITULO { get; set; }
        public Nullable<long> IDMAESTRORESOLUCION { get; set; }
        public Nullable<long> IDDIRECCION { get; set; }
        public Nullable<long> IDMAESTROTIPOLOGIA { get; set; }
        public Nullable<long> IDMAESTROALTERNATIVAPOSTULACION { get; set; }
        public string CODIGOPROYECTOINFORMACIONPROYECTOSOLICITUD { get; set; }
        public string NOMBREPROYECTOINFORMACIONPROYECTOSOLICITUD { get; set; }
        public Nullable<System.DateTime> FECHACALIFICACIONDEFINITIVAINFORMACIONPROYECTOSOLICITUD { get; set; }
        public string RESOLUCIONATINFORMACIONPROYECTOSOLICITUD { get; set; }
        public Nullable<System.DateTime> FECHARESOLUCIONATINFORMACIONPROYECTOSOLICITUD { get; set; }
        public Nullable<int> CANTIDADVIVIENDASINFORMACIONPROYECTOSOLICITUD { get; set; }
        public Nullable<int> CANTIDADBENEFICIARIOSINFORMACIONPROYECTOSOLICITUD { get; set; }
        public Nullable<decimal> MONTOSUBSIDIOBASEINFORMACIONPROYECTOSOLICITUD { get; set; }
        public Nullable<decimal> MONTOSUBSIDIOBASEFACTIBILIDADINFORMACIONPROYECTOSOLICITUD { get; set; }
        public Nullable<bool> MARCALOCALIZACIONINFORMACIONPROYECTOSOLICITUD { get; set; }
        public Nullable<bool> MARCAFACTIBILIZACIONINFORMACIONPROYECTOSOLICITUD { get; set; }
        public Nullable<System.DateTime> FECHAFACTIBILIZACIONINFORMACIONPROYECTOSOLICITUD { get; set; }
        public Nullable<int> NUMEROFAMILIASADSCRITASINFORMACIONPROYECTOSOLICITUD { get; set; }
        public Nullable<int> AGNOFACTIBILIDADINFORMACIONPROYECTOSOLICITUD { get; set; }
        public Nullable<long> IDMAESTROESTADOPROYECTO { get; set; }
        public System.DateTime FECHAINGRESOINFORMACIONPROYECTOSOLICITUD { get; set; }
        public Nullable<long> IDMAESTROESTADOBENEFICIO { get; set; }
        public Nullable<long> IDMAESTROBANCO { get; set; }
        public Nullable<decimal> AVANCEOBRAINFORMACIONPROYECTOSOLICITUD { get; set; }
        public string ESTADOAVANCEOBRAINFORMACIONPROYECTOSOLICITUD { get; set; }
        public Nullable<bool> PERMISOUSUARIOADMINISTRATIVOINFORMACIONPROYECTOSOLICITUD { get; set; }
        public string NOMBREUSUARIOOTORGAPERMISOINFORMACIONPROYECTOSOLICITUD { get; set; }
        public Nullable<long> CodigoInternoSNATInformacionProyectoSolicitud { get; set; }
    
        public virtual DIRECCION DIRECCION { get; set; }
        public virtual INFORMACION_PROYECTO INFORMACION_PROYECTO { get; set; }
        public virtual MAESTRO_BANCO MAESTRO_BANCO { get; set; }
        public virtual MAESTRO_ESTADO_BENEFICIO MAESTRO_ESTADO_BENEFICIO { get; set; }
        public virtual MAESTRO_ALTERNATIVA_POSTULACION MAESTRO_ALTERNATIVA_POSTULACION { get; set; }
        public virtual MAESTRO_LLAMADO MAESTRO_LLAMADO { get; set; }
        public virtual MAESTRO_MODALIDAD MAESTRO_MODALIDAD { get; set; }
        public virtual MAESTRO_PROGRAMA MAESTRO_PROGRAMA { get; set; }
        public virtual MAESTRO_RESOLUCION MAESTRO_RESOLUCION { get; set; }
        public virtual MAESTRO_TIPOLOGIA MAESTRO_TIPOLOGIA { get; set; }
        public virtual MAESTRO_TITULO MAESTRO_TITULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD_PAGO> SOLICITUD_PAGO { get; set; }
    }
}
