//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORMACION_PROYECTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFORMACION_PROYECTO()
        {
            this.BENEFICIARIO = new HashSet<BENEFICIARIO>();
            this.CARACTERISTICAS_ESPECIALES = new HashSet<CARACTERISTICAS_ESPECIALES>();
            this.INFORMACION_PROYECTO_SOLICITUD = new HashSet<INFORMACION_PROYECTO_SOLICITUD>();
            this.TIPO_PROVEEDOR_INFORMACION_PROYECTO = new HashSet<TIPO_PROVEEDOR_INFORMACION_PROYECTO>();
        }
    
        public long IDINFORMACIONPROYECTO { get; set; }
        public Nullable<long> IDDIRECCION { get; set; }
        public Nullable<long> IDMAESTROTITULO { get; set; }
        public Nullable<long> IDMAESTROMODALIDAD { get; set; }
        public Nullable<long> IDMAESTROLLAMADO { get; set; }
        public Nullable<long> IDMAESTROALTERNATIVAPOSTULACION { get; set; }
        public string CODIGOPROYECTOINFORMACIONPROYECTO { get; set; }
        public string NOMBREPROYECTOINFORMACIONPROYECTO { get; set; }
        public Nullable<System.DateTime> FECHACALIFICACIONDEFINITIVAINFORMACIONPROYECTO { get; set; }
        public Nullable<bool> ESTADOPROYECTOINFORMACIONPROYECTO { get; set; }
        public string RESOLUCIONATINFORMACIONPROYECTO { get; set; }
        public Nullable<System.DateTime> FECHARESOLUCIONATINFORMACIONPROYECTO { get; set; }
        public Nullable<int> CANTIDADVIVIENDASINFORMACIONPROYECTO { get; set; }
        public Nullable<int> CANTIDADBENEFICIARIOSINFORMACIONPROYECTO { get; set; }
        public Nullable<long> IDMAESTROPROGRAMA { get; set; }
        public Nullable<decimal> MONTOSUBSIDIOBASEINFORMACIONPROYECTO { get; set; }
        public Nullable<decimal> MONTOSUBSIDIOBASEFACTIBILIDADINFORMACIONPROYECTO { get; set; }
        public Nullable<bool> MARCALOCALIZACIONINFORMACIONPROYECTO { get; set; }
        public Nullable<bool> MARCAFACTIBILIZACIONINFORMACIONPROYECTO { get; set; }
        public Nullable<System.DateTime> FECHAFACTIBILIZACIONINFORMACIONPROYECTO { get; set; }
        public Nullable<int> NUMEROFAMILIASADSCRITASINFORMACIONPROYECTO { get; set; }
        public Nullable<long> IDMAESTRORESOLUCION { get; set; }
        public Nullable<int> AGNOFACTIBILIDADINFORMACIONPROYECTO { get; set; }
        public Nullable<long> IDMAESTROESTADOPROYECTO { get; set; }
        public Nullable<long> IDMAESTROESTADOBENEFICIO { get; set; }
        public Nullable<long> IDMAESTROBANCO { get; set; }
        public Nullable<decimal> AVANCEOBRAINFORMACIONPROYECTO { get; set; }
        public string ESTADOAVANCEOBRAINFORMACIONPROYECTO { get; set; }
        public Nullable<bool> PERMISOUSUARIOADMINISTRATIVOINFORMACIONPROYECTO { get; set; }
        public string NOMBREUSUARIOOTORGAPERMISOINFORMACIONPROYECTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BENEFICIARIO> BENEFICIARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARACTERISTICAS_ESPECIALES> CARACTERISTICAS_ESPECIALES { get; set; }
        public virtual DIRECCION DIRECCION { get; set; }
        public virtual MAESTRO_BANCO MAESTRO_BANCO { get; set; }
        public virtual MAESTRO_ESTADO_BENEFICIO MAESTRO_ESTADO_BENEFICIO { get; set; }
        public virtual MAESTRO_PROGRAMA MAESTRO_PROGRAMA { get; set; }
        public virtual MAESTRO_RESOLUCION MAESTRO_RESOLUCION { get; set; }
        public virtual MAESTRO_ESTADO_PROYECTO MAESTRO_ESTADO_PROYECTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFORMACION_PROYECTO_SOLICITUD> INFORMACION_PROYECTO_SOLICITUD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_PROVEEDOR_INFORMACION_PROYECTO> TIPO_PROVEEDOR_INFORMACION_PROYECTO { get; set; }
        public virtual MAESTRO_ALTERNATIVA_POSTULACION MAESTRO_ALTERNATIVA_POSTULACION { get; set; }
        public virtual MAESTRO_LLAMADO MAESTRO_LLAMADO { get; set; }
        public virtual MAESTRO_MODALIDAD MAESTRO_MODALIDAD { get; set; }
        public virtual MAESTRO_TITULO MAESTRO_TITULO { get; set; }
    }
}
