//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAESTRO_ESTADO_BENEFICIARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAESTRO_ESTADO_BENEFICIARIO()
        {
            this.BENEFICIARIO = new HashSet<BENEFICIARIO>();
        }
    
        public long IDMAESTROESTADOBENEFICIARIO { get; set; }
        public string NOMBREMAESTROESTADOBENEFICIARIO { get; set; }
        public bool ESTADOMAESTROESTADOBENEFICIARIO { get; set; }
        public Nullable<long> IDMAESTROPROGRAMA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BENEFICIARIO> BENEFICIARIO { get; set; }
        public virtual MAESTRO_PROGRAMA MAESTRO_PROGRAMA { get; set; }
    }
}
