//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAESTRO_SERVICIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAESTRO_SERVICIO()
        {
            this.TIPO_ACTIVIDAD_MONTO = new HashSet<TIPO_ACTIVIDAD_MONTO>();
            this.TIPO_SERVICIOS_CONTRATO = new HashSet<TIPO_SERVICIOS_CONTRATO>();
            this.TIPOLOGIA_SERVICIO = new HashSet<TIPOLOGIA_SERVICIO>();
        }
    
        public long IDMAESTROSERVICIO { get; set; }
        public string NOMBREMAESTROSERVICIO { get; set; }
        public Nullable<bool> ESTADOMAESTROSERVICIO { get; set; }
        public string NOMBREABREVIADOMAESTROSERVICIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_ACTIVIDAD_MONTO> TIPO_ACTIVIDAD_MONTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_SERVICIOS_CONTRATO> TIPO_SERVICIOS_CONTRATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPOLOGIA_SERVICIO> TIPOLOGIA_SERVICIO { get; set; }
    }
}
