//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAESTRO_INFORMACION_SISTEMA_EXTERNO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAESTRO_INFORMACION_SISTEMA_EXTERNO()
        {
            this.HOMOLOGACION_INFORMACION_SISTEMA = new HashSet<HOMOLOGACION_INFORMACION_SISTEMA>();
        }
    
        public long IDMAESTROINFORMACIONSISTEMAEXTERNO { get; set; }
        public string DESCRIPCIONMAESTROINFORMACIONSISTEMAEXTERNO { get; set; }
        public string VALORIDMAESTROINFORMACIONSISTEMAEXTERNO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOMOLOGACION_INFORMACION_SISTEMA> HOMOLOGACION_INFORMACION_SISTEMA { get; set; }
    }
}
