//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAESTRO_TIPO_PROVEEDOR_SISTEMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAESTRO_TIPO_PROVEEDOR_SISTEMA()
        {
            this.MAESTRO_TIPO_PROVEEDOR = new HashSet<MAESTRO_TIPO_PROVEEDOR>();
        }
    
        public long IDMAESTROTIPOPROVEEDORSISTEMA { get; set; }
        public string NOMBREMAESTROTIPOPROVEEDORSISTEMA { get; set; }
        public Nullable<bool> ESTADOMAESTROTIPOPROVEEDORSISTEMA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAESTRO_TIPO_PROVEEDOR> MAESTRO_TIPO_PROVEEDOR { get; set; }
    }
}
