//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAESTRO_INCREMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAESTRO_INCREMENTO()
        {
            this.TIPO_INCREMENTO = new HashSet<TIPO_INCREMENTO>();
        }
    
        public long IDMAESTROINCREMENTO { get; set; }
        public string NOMBREMAESTROINCREMENTO { get; set; }
        public Nullable<bool> ESTADOMAESTROINCREMENTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_INCREMENTO> TIPO_INCREMENTO { get; set; }
    }
}
