//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAESTRO_ESTADO_AUTORIZACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAESTRO_ESTADO_AUTORIZACION()
        {
            this.AUTORIZACION = new HashSet<AUTORIZACION>();
        }
    
        public long IDMAESTROESTADOAUTORIZACION { get; set; }
        public string NOMBREMAESTROESTADOAUTORIZACION { get; set; }
        public Nullable<bool> ESTADOMAESTROESTADOAUTORIZACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTORIZACION> AUTORIZACION { get; set; }
    }
}
