//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAESTRO_PROGRAMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAESTRO_PROGRAMA()
        {
            this.AUTORIZACION = new HashSet<AUTORIZACION>();
            this.CARACTERISTICAS_ESPECIALES = new HashSet<CARACTERISTICAS_ESPECIALES>();
            this.CONVALIDACION_PROGRAMA_SISTEMA = new HashSet<CONVALIDACION_PROGRAMA_SISTEMA>();
            this.INFORMACION_PROYECTO = new HashSet<INFORMACION_PROYECTO>();
            this.INFORMACION_PROYECTO_SOLICITUD = new HashSet<INFORMACION_PROYECTO_SOLICITUD>();
            this.MAESTRO_ESTADO_BENEFICIARIO = new HashSet<MAESTRO_ESTADO_BENEFICIARIO>();
            this.MAESTRO_RESOLUCION = new HashSet<MAESTRO_RESOLUCION>();
            this.MAESTRO_TIPO_INGRESO = new HashSet<MAESTRO_TIPO_INGRESO>();
            this.SERVICIO_PARCIALIDAD = new HashSet<SERVICIO_PARCIALIDAD>();
        }
    
        public long IDMAESTROPROGRAMA { get; set; }
        public string NOMBREMAESTROPROGRAMA { get; set; }
        public Nullable<bool> ESTADOMAESTROPROGRAMA { get; set; }
        public Nullable<int> CODIGOENTRAZABILIDAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTORIZACION> AUTORIZACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARACTERISTICAS_ESPECIALES> CARACTERISTICAS_ESPECIALES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONVALIDACION_PROGRAMA_SISTEMA> CONVALIDACION_PROGRAMA_SISTEMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFORMACION_PROYECTO> INFORMACION_PROYECTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFORMACION_PROYECTO_SOLICITUD> INFORMACION_PROYECTO_SOLICITUD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAESTRO_ESTADO_BENEFICIARIO> MAESTRO_ESTADO_BENEFICIARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAESTRO_RESOLUCION> MAESTRO_RESOLUCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAESTRO_TIPO_INGRESO> MAESTRO_TIPO_INGRESO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIO_PARCIALIDAD> SERVICIO_PARCIALIDAD { get; set; }
    }
}
