//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAESTRO_CLASE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAESTRO_CLASE()
        {
            this.CARACTERISTICAS_ESPECIALES = new HashSet<CARACTERISTICAS_ESPECIALES>();
        }
    
        public long IDMAESTROCLASE { get; set; }
        public string NOMBREMAESTROCLASE { get; set; }
        public Nullable<bool> ESTADOMAESTROCLASE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARACTERISTICAS_ESPECIALES> CARACTERISTICAS_ESPECIALES { get; set; }
    }
}
