//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAESTRO_TIPOLOGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAESTRO_TIPOLOGIA()
        {
            this.AUTORIZACION = new HashSet<AUTORIZACION>();
            this.CARACTERISTICAS_ESPECIALES = new HashSet<CARACTERISTICAS_ESPECIALES>();
            this.INFORMACION_PROYECTO_SOLICITUD = new HashSet<INFORMACION_PROYECTO_SOLICITUD>();
            this.TIPOLOGIA_SERVICIO = new HashSet<TIPOLOGIA_SERVICIO>();
        }
    
        public long IDMAESTROTIPOLOGIA { get; set; }
        public string NOMBREMAESTROTIPOLOGIA { get; set; }
        public Nullable<bool> ESTADOMAESTROTIPOLOGIA { get; set; }
        public string NOMBREABREVIADOMAESTROTIPOLOGIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTORIZACION> AUTORIZACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARACTERISTICAS_ESPECIALES> CARACTERISTICAS_ESPECIALES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFORMACION_PROYECTO_SOLICITUD> INFORMACION_PROYECTO_SOLICITUD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPOLOGIA_SERVICIO> TIPOLOGIA_SERVICIO { get; set; }
    }
}
