//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAESTRO_TIPO_DESTINO_PAGO
    {
        public long IDMAESTROTIPODESTINOPAGO { get; set; }
        public string NOMBREMAESTROTIPODESTINOPAGO { get; set; }
        public Nullable<bool> ESTADOMAESTROTIPODESTINOPAGO { get; set; }
    }
}
