//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAESTRO_TIPO_PROVEEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAESTRO_TIPO_PROVEEDOR()
        {
            this.CONTRATO_ATP = new HashSet<CONTRATO_ATP>();
            this.PROVEEDOR = new HashSet<PROVEEDOR>();
        }
    
        public long IDMAESTROTIPOPROVEEDOR { get; set; }
        public string NOMBREMAESTROTIPOPROVEEDOR { get; set; }
        public Nullable<bool> ESTADOMAESTROTIPOPROVEEDOR { get; set; }
        public Nullable<long> IDMAESTROTIPOPROVEEDORSISTEMA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATO_ATP> CONTRATO_ATP { get; set; }
        public virtual MAESTRO_TIPO_PROVEEDOR_SISTEMA MAESTRO_TIPO_PROVEEDOR_SISTEMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROVEEDOR> PROVEEDOR { get; set; }
    }
}
