//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAESTRO_RESOLUCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAESTRO_RESOLUCION()
        {
            this.INFORMACION_PROYECTO = new HashSet<INFORMACION_PROYECTO>();
            this.INFORMACION_PROYECTO_SOLICITUD = new HashSet<INFORMACION_PROYECTO_SOLICITUD>();
        }
    
        public long IDMAESTRORESOLUCION { get; set; }
        public string NOMBREMAESTRORESOLUCION { get; set; }
        public Nullable<bool> ESTADOMAESTRORESOLUCION { get; set; }
        public Nullable<System.DateTime> FECHAMAESTRORESOLUCION { get; set; }
        public Nullable<long> IDMAESTROPROGRAMA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFORMACION_PROYECTO> INFORMACION_PROYECTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFORMACION_PROYECTO_SOLICITUD> INFORMACION_PROYECTO_SOLICITUD { get; set; }
        public virtual MAESTRO_PROGRAMA MAESTRO_PROGRAMA { get; set; }
    }
}
