//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAESTRO_ESTADO_PROYECTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAESTRO_ESTADO_PROYECTO()
        {
            this.INFORMACION_PROYECTO = new HashSet<INFORMACION_PROYECTO>();
        }
    
        public long IDMAESTROESTADOPROYECTO { get; set; }
        public string NOMBREMAESTROESTADOPROYECTO { get; set; }
        public bool ESTADOMAESTROESTADOPROYECTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFORMACION_PROYECTO> INFORMACION_PROYECTO { get; set; }
    }
}
