//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAESTRO_PARCIALIDAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAESTRO_PARCIALIDAD()
        {
            this.SUB_MODALIDAD_PARCIALIDAD = new HashSet<SUB_MODALIDAD_PARCIALIDAD>();
        }
    
        public long IDMAESTROPARCIALIDAD { get; set; }
        public string NOMBREMAESTROPARCIALIDAD { get; set; }
        public Nullable<bool> ESTADOMAESTROPARCIALIDAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUB_MODALIDAD_PARCIALIDAD> SUB_MODALIDAD_PARCIALIDAD { get; set; }
    }
}
