//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODIFICACION_ESTADO_SOLICITUD
    {
        public long IDMODIFICACIONESTADOSOLICITUD { get; set; }
        public long IDSOLICITUDPAGO { get; set; }
        public long IDMAESTROESTADOSOLICITUD { get; set; }
        public System.DateTime FECHAMODIFICACIONESTADOSOLICITUD { get; set; }
        public string USUARIORESPONSABLEMODIFICACIONESTADOSOLICITUD { get; set; }
    
        public virtual MAESTRO_ESTADO_SOLICITUD MAESTRO_ESTADO_SOLICITUD { get; set; }
        public virtual SOLICITUD_PAGO SOLICITUD_PAGO { get; set; }
    }
}
