//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Web_Trazabilidad_Test_Entities : DbContext
    {
        public Web_Trazabilidad_Test_Entities()
            : base("name=Web_Trazabilidad_Test_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<WEB_TRAZABILIDAD_ups_con_PROYECTO_AVANCE_OBRA_SNAT_SIMPLIFICADO_Result> WEB_TRAZABILIDAD_ups_con_PROYECTO_AVANCE_OBRA_SNAT_SIMPLIFICADO(Nullable<int> programa, string codigoProyecto, Nullable<int> region, Nullable<int> titulo, Nullable<int> año, Nullable<int> numerollamado)
        {
            var programaParameter = programa.HasValue ?
                new ObjectParameter("Programa", programa) :
                new ObjectParameter("Programa", typeof(int));
    
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            var regionParameter = region.HasValue ?
                new ObjectParameter("Region", region) :
                new ObjectParameter("Region", typeof(int));
    
            var tituloParameter = titulo.HasValue ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(int));
    
            var añoParameter = año.HasValue ?
                new ObjectParameter("Año", año) :
                new ObjectParameter("Año", typeof(int));
    
            var numerollamadoParameter = numerollamado.HasValue ?
                new ObjectParameter("Numerollamado", numerollamado) :
                new ObjectParameter("Numerollamado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_TRAZABILIDAD_ups_con_PROYECTO_AVANCE_OBRA_SNAT_SIMPLIFICADO_Result>("WEB_TRAZABILIDAD_ups_con_PROYECTO_AVANCE_OBRA_SNAT_SIMPLIFICADO", programaParameter, codigoProyectoParameter, regionParameter, tituloParameter, añoParameter, numerollamadoParameter);
        }
    }
}
