//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESUPUESTO_REGIONAL
    {
        public long IDPRESUPUESTOREGIONAL_ { get; set; }
        public Nullable<int> IDRESOLUCIONPRESUPUESTARIA { get; set; }
        public Nullable<int> CODIGOREGIONPRESUPUESTOREGIONAL { get; set; }
        public Nullable<long> MONTOPRESUPUESTOREGIONAL { get; set; }
        public string USUARIOPRESUPUESTOREGIONAL { get; set; }
        public Nullable<System.DateTime> FECHAPRESUPUESTOREGIONAL { get; set; }
    
        public virtual RESOLUCION_PRESUPUESTARIA RESOLUCION_PRESUPUESTARIA { get; set; }
    }
}
