//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESOLUCION_PRESUPUESTARIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESOLUCION_PRESUPUESTARIA()
        {
            this.PRESUPUESTO_REGIONAL = new HashSet<PRESUPUESTO_REGIONAL>();
        }
    
        public int IDRESOLUCIONPRESUPUESTARIA { get; set; }
        public Nullable<short> ANORESOLUCIONPRESUPUESTARIA { get; set; }
        public Nullable<int> NUMERORESOLUCIONPRESUPUESTARIA { get; set; }
        public Nullable<System.DateTime> FECHARESOLUCIONPRESUPUESTARIA { get; set; }
        public string USUARIORESOLUCIONPRESUPUESTARIA { get; set; }
        public string NOMBREARCHIVOPRESUPUESTO { get; set; }
        public Nullable<bool> ESTADORESOLUCIONPRESUPUESTARIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESUPUESTO_REGIONAL> PRESUPUESTO_REGIONAL { get; set; }
    }
}
