//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO_PARCIALIDAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICIO_PARCIALIDAD()
        {
            this.TIPO_SERVICIO_PARCIALIDAD_CARACTERISTICA = new HashSet<TIPO_SERVICIO_PARCIALIDAD_CARACTERISTICA>();
        }
    
        public Nullable<long> IDSUBMODALIDADPARCIALIDAD { get; set; }
        public Nullable<long> IDGRUPOSUBMODALIDADPARCIALIDAD { get; set; }
        public Nullable<long> IDTIPOLOGIASERVICIO { get; set; }
        public Nullable<long> IDGRUPOTIPOLOGIASERVICIO { get; set; }
        public long IDSERVICIOPARCIALIDAD { get; set; }
        public Nullable<int> NUMEROPLANTILLASERVICIOPARCIALIDAD { get; set; }
        public string OBSERVACIONSERVICIOPARCIALIDAD { get; set; }
        public Nullable<long> IDMAESTROPROGRAMA { get; set; }
        public Nullable<bool> ESTADOSERVICIOPARCIALIDAD { get; set; }
    
        public virtual MAESTRO_PROGRAMA MAESTRO_PROGRAMA { get; set; }
        public virtual SUB_MODALIDAD_PARCIALIDAD SUB_MODALIDAD_PARCIALIDAD { get; set; }
        public virtual TIPOLOGIA_SERVICIO TIPOLOGIA_SERVICIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_SERVICIO_PARCIALIDAD_CARACTERISTICA> TIPO_SERVICIO_PARCIALIDAD_CARACTERISTICA { get; set; }
    }
}
