//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD_AUTORIZACION
    {
        public long IDSOLICITUDAUTORIZACION { get; set; }
        public long NUMEROAUTORIZACIONSOLICITUDAUTORIZACION { get; set; }
        public Nullable<long> NUMEROSOLICITUDSOLICITUDAUTORIZACION { get; set; }
        public Nullable<long> CODIGOPROYECTOSOLICITUDAUTORIZACION { get; set; }
        public string NOMBREPROYECTOSOLICITUDAUTORIZACION { get; set; }
        public string UBICACIONCOMUNASOLICITUDAUTORIZACION { get; set; }
        public Nullable<decimal> S1SOLICITUDAUTORIZACION { get; set; }
        public Nullable<decimal> S2SOLICITUDAUTORIZACION { get; set; }
        public Nullable<decimal> S3SOLICITUDAUTORIZACION { get; set; }
        public Nullable<decimal> S4SOLICITUDAUTORIZACION { get; set; }
        public Nullable<decimal> S5SOLICITUDAUTORIZACION { get; set; }
        public Nullable<decimal> S6SOLICITUDAUTORIZACION { get; set; }
        public Nullable<decimal> S7SOLICITUDAUTORIZACION { get; set; }
        public Nullable<decimal> S8SOLICITUDAUTORIZACION { get; set; }
        public Nullable<decimal> S9SOLICITUDAUTORIZACION { get; set; }
        public Nullable<decimal> S10SOLICITUDAUTORIZACION { get; set; }
        public Nullable<decimal> FTOSOLICITUDAUTORIZACION { get; set; }
        public Nullable<decimal> MONTOFTOTOTALSOLICITUDAUTORIZACION { get; set; }
        public Nullable<decimal> MONTOATSOLICITUDAUTORIZACION { get; set; }
        public Nullable<decimal> MONTOAPAGOSOLICITUDAUTORIZACION { get; set; }
    }
}
