//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD_PAGO_ATP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOLICITUD_PAGO_ATP()
        {
            this.TIPO_ACTIVIDAD_MONTO = new HashSet<TIPO_ACTIVIDAD_MONTO>();
        }
    
        public long IDSOLICITUDATP { get; set; }
        public Nullable<long> IDCONTRATOATP { get; set; }
        public Nullable<int> AGNOPRESUPUESTOSOLICITUDPAGOATP { get; set; }
        public Nullable<decimal> PRESUPUESTOREGIONALSOLICITUDPAGOATP { get; set; }
        public Nullable<int> CODIGOREGIONSOLICITUDPAGOATP { get; set; }
        public Nullable<decimal> MONTOPAGADOSOLICITUDPAGOATP { get; set; }
        public Nullable<decimal> MONTOCOMPROMETIDOSOLICITUDPAGOATP { get; set; }
        public Nullable<decimal> MONTOPORPAGARSOLICITUDPAGOATP { get; set; }
        public Nullable<long> NUMEROBOLETAFACTURASOLICITUDPAGOATP { get; set; }
        public Nullable<System.DateTime> FECHABOLETAFACTURASOLICITUDPAGOATP { get; set; }
        public Nullable<decimal> MONTOTOTALAPAGARSOLICITUDPAGOATP { get; set; }
        public Nullable<bool> VBSERVICIOSOLICITUDPAGOATP { get; set; }
        public string VBRESPONSABLESOLICITUDPAGOATP { get; set; }
        public Nullable<System.DateTime> VBFECHASOLICITUDPAGOATP { get; set; }
        public Nullable<long> IDMAESTROESTADOSOLICITUD { get; set; }
        public Nullable<System.DateTime> FECHACREACIONSOLICITUDPAGOATP { get; set; }
        public string USUARIOCREACIONSOLICITUDPAGOATP { get; set; }
        public Nullable<long> IDMAESTROTIPOPAGO { get; set; }
        public Nullable<System.DateTime> FECHAINYECCIONAUTORIZACION { get; set; }
        public Nullable<long> VALORUFPESOAUTORIZACION { get; set; }
        public Nullable<long> MONTOPESOAUTORIZACION { get; set; }
    
        public virtual CONTRATO_ATP CONTRATO_ATP { get; set; }
        public virtual MAESTRO_ESTADO_SOLICITUD MAESTRO_ESTADO_SOLICITUD { get; set; }
        public virtual MAESTRO_TIPO_PAGO MAESTRO_TIPO_PAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_ACTIVIDAD_MONTO> TIPO_ACTIVIDAD_MONTO { get; set; }
    }
}
