//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD_PAGO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOLICITUD_PAGO()
        {
            this.MODIFICACION_ESTADO_SOLICITUD = new HashSet<MODIFICACION_ESTADO_SOLICITUD>();
            this.TIPO_AUTORIZACION = new HashSet<TIPO_AUTORIZACION>();
            this.TIPO_SERVICIO_PARCIALIDAD_CARACTERISTICA = new HashSet<TIPO_SERVICIO_PARCIALIDAD_CARACTERISTICA>();
            this.TIPO_INCREMENTO = new HashSet<TIPO_INCREMENTO>();
            this.TIPO_SERVICIO = new HashSet<TIPO_SERVICIO>();
        }
    
        public long IDSOLICITUDPAGO { get; set; }
        public Nullable<long> IDMAESTROESTADOSOLICITUD { get; set; }
        public string FOLIOBOLETAGARANTIASOLICITUDPAGO { get; set; }
        public Nullable<int> NUMEROFAMILIASPAGARSOLICITUDPAGO { get; set; }
        public string USUARIORESPONSABLESOLICITUDPAGO { get; set; }
        public Nullable<long> IDCARACTERISTICASESPECIALES { get; set; }
        public Nullable<long> IDMAESTROTIPOPAGO { get; set; }
        public Nullable<System.DateTime> FECHAREALCREACIONSOLICITUDPAGO { get; set; }
        public Nullable<System.DateTime> FECHACREACIONSOLICITUDPAGO { get; set; }
        public Nullable<long> IDMAESTROTIPODESTINOPAGO { get; set; }
        public Nullable<decimal> MONTOTOTALPROYECTOSOLICITUDPAGO { get; set; }
        public Nullable<decimal> MONTOPAGADOSOLICITUDPAGO { get; set; }
        public Nullable<decimal> MONTOCOMPROMETIDOSOLICITUDPAGO { get; set; }
        public Nullable<decimal> SALDOPORPAGARSOLICITUDPAGO { get; set; }
        public Nullable<decimal> AVANCEOBRASOLICITUDPAGO { get; set; }
        public Nullable<long> NUMERORESOLUCIONCONTRATOSOLICITUDPAGO { get; set; }
        public Nullable<decimal> MONTOSOLICITUDSOLICITUDPAGO { get; set; }
        public Nullable<long> IDPROVEEDOR { get; set; }
        public Nullable<int> NUMEROVIVIENDASSOLICITUDPAGO { get; set; }
        public Nullable<long> IDINFORMACIONPROYECTOSOLICITUD { get; set; }
        public string OBSERVACIONESSOLICITUDPAGO { get; set; }
        public Nullable<System.DateTime> FECHARESOLUCIONSOLICITUDPAGO { get; set; }
        public Nullable<long> IDMAESTROPROGRAMA { get; set; }
        public Nullable<System.DateTime> FECHABOLETAGARANTIASOLICITUDPAGO { get; set; }
        public Nullable<bool> PAGOMANDANTOSOLICITUDPAGO { get; set; }
        public Nullable<long> IDMANDANTOPROVEEDORSOLICITUDPAGO { get; set; }
    
        public virtual CARACTERISTICAS_ESPECIALES CARACTERISTICAS_ESPECIALES { get; set; }
        public virtual INFORMACION_PROYECTO_SOLICITUD INFORMACION_PROYECTO_SOLICITUD { get; set; }
        public virtual MAESTRO_ESTADO_SOLICITUD MAESTRO_ESTADO_SOLICITUD { get; set; }
        public virtual MAESTRO_TIPO_PAGO MAESTRO_TIPO_PAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MODIFICACION_ESTADO_SOLICITUD> MODIFICACION_ESTADO_SOLICITUD { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual PROVEEDOR PROVEEDOR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_AUTORIZACION> TIPO_AUTORIZACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_SERVICIO_PARCIALIDAD_CARACTERISTICA> TIPO_SERVICIO_PARCIALIDAD_CARACTERISTICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_INCREMENTO> TIPO_INCREMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_SERVICIO> TIPO_SERVICIO { get; set; }
    }
}
