//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_MODALIDAD_PARCIALIDAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUB_MODALIDAD_PARCIALIDAD()
        {
            this.SERVICIO_PARCIALIDAD = new HashSet<SERVICIO_PARCIALIDAD>();
        }
    
        public long IDSUBMODALIDADPARCIALIDAD { get; set; }
        public Nullable<long> IDMAESTROPARCIALIDAD { get; set; }
        public Nullable<long> IDMAESTROSUBMODALIDAD { get; set; }
        public long IDGRUPOSUBMODALIDADPARCIALIDAD { get; set; }
    
        public virtual MAESTRO_PARCIALIDAD MAESTRO_PARCIALIDAD { get; set; }
        public virtual MAESTRO_SUB_MODALIDAD MAESTRO_SUB_MODALIDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIO_PARCIALIDAD> SERVICIO_PARCIALIDAD { get; set; }
    }
}
