//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TERRITORIO_CONTRATO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TERRITORIO_CONTRATO()
        {
            this.CONTRATO_ATP = new HashSet<CONTRATO_ATP>();
        }
    
        public long IDTERRITORIOCONTRATO { get; set; }
        public Nullable<long> CODIGOPROVINCIATERRITORIOCONTRATO { get; set; }
        public Nullable<long> CODIGOREGIONTERRITORIOCONTRATO { get; set; }
        public Nullable<long> CODIGOCOMUNATERRITORIOCONTRATO { get; set; }
        public Nullable<bool> ESTADOTERRITORIOCONTRATO { get; set; }
        public Nullable<System.DateTime> FECHACREACIONTERRITORIOCONTRATO { get; set; }
        public Nullable<System.DateTime> FECHAACTUALIZACIONTERRITORIOCONTRATO { get; set; }
        public string USUARIOTERRITORIOCONTRATO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATO_ATP> CONTRATO_ATP { get; set; }
    }
}
