//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_SERVICIOS_CONTRATO
    {
        public long IDTIPOSERVICIOSCONTRATO { get; set; }
        public Nullable<long> IDMAESTROSERVICIO { get; set; }
        public Nullable<long> IDCONTRATOATP { get; set; }
        public Nullable<bool> ESTADOTIPOSERVICIOSCONTRATO { get; set; }
    
        public virtual CONTRATO_ATP CONTRATO_ATP { get; set; }
        public virtual MAESTRO_SERVICIO MAESTRO_SERVICIO { get; set; }
    }
}
