//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_SERVICIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_SERVICIO()
        {
            this.TIPO_PARCIALIDAD = new HashSet<TIPO_PARCIALIDAD>();
        }
    
        public long IDTIPOSERVICIO { get; set; }
        public Nullable<long> IDSOLICITUDPAGO { get; set; }
        public Nullable<decimal> MONTOASIGNACIONDIRECTATIPOSERVICIO { get; set; }
        public Nullable<decimal> TOTALSERVICIOTIPOSERVICIO { get; set; }
        public Nullable<decimal> MONTOINCREMENTOTIPOSERVICIO { get; set; }
    
        public virtual SOLICITUD_PAGO SOLICITUD_PAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_PARCIALIDAD> TIPO_PARCIALIDAD { get; set; }
    }
}
