//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_ACTIVIDAD_MONTO
    {
        public long IDTIPOACTIVIDADMONTO { get; set; }
        public Nullable<long> IDSOLICITUDATP { get; set; }
        public string TIPOSERVICIOTIPOACTIVIDADMONTO { get; set; }
        public Nullable<long> IDMAESTROSERVICIO { get; set; }
        public Nullable<decimal> MONTOPAGOTIPOACTIVIDADMONTO { get; set; }
    
        public virtual MAESTRO_SERVICIO MAESTRO_SERVICIO { get; set; }
        public virtual SOLICITUD_PAGO_ATP SOLICITUD_PAGO_ATP { get; set; }
    }
}
