//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_SERVICIO_PARCIALIDAD_CARACTERISTICA
    {
        public long IDTIPOSERVICIOPARCIALIDADCARACTERISTICA { get; set; }
        public Nullable<long> IDSERVICIOPARCIALIDAD { get; set; }
        public Nullable<long> IDCARACTERISTICASESPECIALES { get; set; }
        public Nullable<bool> ESTADOTIPOSERVICIOPARCIALIDADCARACTERISTICA { get; set; }
        public Nullable<decimal> MONTOSERVICIOTIPOSERVICIOPARCIALIDADCARACTERISTICA { get; set; }
        public Nullable<decimal> MONTOPARCIALIDADTIPOSERVICIOPARCIALIDADCARACTERISTICA { get; set; }
        public Nullable<int> PORCENTAJEPARCIALIDADTIPOSERVICIOPARCIALIDADCARACTERISTICA { get; set; }
        public Nullable<long> IDSOLICITUDPAGO { get; set; }
        public Nullable<decimal> MONTOASIGNACIONDIRECTATIPOSERVICIOPARCIALIDADCARACTERISTICA { get; set; }
    
        public virtual CARACTERISTICAS_ESPECIALES CARACTERISTICAS_ESPECIALES { get; set; }
        public virtual SERVICIO_PARCIALIDAD SERVICIO_PARCIALIDAD { get; set; }
        public virtual SOLICITUD_PAGO SOLICITUD_PAGO { get; set; }
    }
}
