//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_PARCIALIDAD
    {
        public long IDTIPOPARCIALIDAD { get; set; }
        public Nullable<long> IDTIPOSERVICIO { get; set; }
        public Nullable<bool> ESTADOTIPOPARCIALIDAD { get; set; }
        public Nullable<decimal> PORCENTAJETIPOPARCIALIDAD { get; set; }
    
        public virtual TIPO_SERVICIO TIPO_SERVICIO { get; set; }
    }
}
