//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public string UserName { get; set; }
        public decimal Rut { get; set; }
        public string DVRut { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<int> CodigoUnidad { get; set; }
        public Nullable<int> CodigoOrganismo { get; set; }
        public Nullable<int> CodigoEntidad { get; set; }
        public string TipoUsuario { get; set; }
        public string Email { get; set; }
        public string Pregunta { get; set; }
        public string Respuesta { get; set; }
        public bool Habilitado { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> FechaExpiracion { get; set; }
        public Nullable<bool> CambiarPassword { get; set; }
    }
}
