//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_ASISTEC_SNATIII_FAMILIA
    {
        public int FAM_RUT { get; set; }
        public string FAM_DGV { get; set; }
        public Nullable<int> FAM_TIP { get; set; }
        public string FAM_NOM { get; set; }
        public string FAM_APP_PAT { get; set; }
        public string FAM_APP_MAT { get; set; }
        public Nullable<int> REG_COD { get; set; }
        public Nullable<int> COM_COD { get; set; }
        public Nullable<int> PRV_COD { get; set; }
        public string FAM_EST_CIV { get; set; }
        public Nullable<System.DateTime> FAM_FEC_NAC { get; set; }
        public string FAM_NAC { get; set; }
        public string FAM_SEX { get; set; }
        public string FAM_CLL { get; set; }
        public string FAM_CLL_NUM { get; set; }
        public string FAM_BLK { get; set; }
        public string FAM_DEP { get; set; }
        public string FAM_MZN { get; set; }
        public string FAM_SITI { get; set; }
        public string FAM_TIP_VIV { get; set; }
        public string FAM_VIV_ROL { get; set; }
        public string FAM_VIV_NUM_CERT { get; set; }
        public Nullable<System.DateTime> FAM_VIV_FEC_CERT { get; set; }
        public string FAM_VIV_NOM_RSP { get; set; }
        public string FAM_ENT_NOM { get; set; }
        public string FAM_CYG_NOM { get; set; }
        public string FAM_CYG_APP_PAT { get; set; }
        public string FAM_CYG_APP_MAT { get; set; }
        public string FAM_COM_FIC { get; set; }
        public Nullable<decimal> FAM_PJE_FIC { get; set; }
        public Nullable<decimal> FAM_FOL_FIC { get; set; }
        public string FAM_INDC_ALLG { get; set; }
        public string FAM_INDC_TIP_VIV { get; set; }
        public string FAM_INDC_ELIM_AGU { get; set; }
        public string FAM_INDC_HACN { get; set; }
        public string FAM_INDC_AGU { get; set; }
        public Nullable<System.DateTime> FAM_FEC_ING { get; set; }
        public Nullable<int> FAM_EST { get; set; }
        public Nullable<int> FAM_TIP_FND { get; set; }
        public string FAM_TIP_FND_DESC { get; set; }
        public Nullable<int> REG_COD_FAM { get; set; }
        public Nullable<int> COM_COD_FAM { get; set; }
        public Nullable<int> PRV_COD_FAM { get; set; }
        public string FAM_FON { get; set; }
        public string FAM_MAIL { get; set; }
        public string FAM_POB { get; set; }
        public Nullable<int> FAM_DSCA { get; set; }
        public Nullable<int> FAM_RUKAN { get; set; }
        public Nullable<int> FAM_SUB_PAG { get; set; }
        public string FAM_NUM_CER_SUB { get; set; }
        public string FAM_RES_BNF { get; set; }
        public Nullable<int> FAM_SEPR_HECH { get; set; }
        public Nullable<System.DateTime> FAM_FEC_INI_VIG_SUB { get; set; }
        public Nullable<System.DateTime> FAM_FEC_FIN_VIG_SUB { get; set; }
        public Nullable<int> FAM_TIP_LLA { get; set; }
        public string FAM_TIP_LLA_DESC { get; set; }
        public Nullable<int> FAM_CYG_RUT { get; set; }
        public string FAM_CYG_DGV { get; set; }
        public Nullable<System.DateTime> FAM_OBS_FEC { get; set; }
        public string FAM_OBS_FAM { get; set; }
        public string FAM_OBS_VIV { get; set; }
        public string FAM_OBS_SUB { get; set; }
        public string FAM_OBS_USR { get; set; }
        public Nullable<int> FAM_ASG_DRT { get; set; }
        public Nullable<int> FAM_PRY_PISA { get; set; }
        public Nullable<int> FAM_PRG { get; set; }
        public Nullable<decimal> FAM_MTO_VIV_TIP_RUKAN { get; set; }
        public Nullable<int> FAM_ANO_LLA { get; set; }
        public Nullable<int> FAM_TIP_SPS { get; set; }
    }
}
