//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_ASISTEC_SNATIII_PROFESION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WEB_ASISTEC_SNATIII_PROFESION()
        {
            this.WEB_ASISTEC_SNATIII_PROFESIONALES = new HashSet<WEB_ASISTEC_SNATIII_PROFESIONALES>();
        }
    
        public int PROF_PROF_ID { get; set; }
        public string PROF_PROF_NOM { get; set; }
        public int PROF_PROF_EST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WEB_ASISTEC_SNATIII_PROFESIONALES> WEB_ASISTEC_SNATIII_PROFESIONALES { get; set; }
    }
}
