//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_ASISTEC_SNATIII_PPPF_PROYECTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WEB_ASISTEC_SNATIII_PPPF_PROYECTO()
        {
            this.WEB_ASISTEC_SNATIII_PPPF_CONTRATO_PROYECTO = new HashSet<WEB_ASISTEC_SNATIII_PPPF_CONTRATO_PROYECTO>();
        }
    
        public int PPPF_PRY_ID { get; set; }
        public string PPPF_PRY_COD { get; set; }
        public string PPPF_PRY_CER { get; set; }
        public string PPPF_PRY_NOM { get; set; }
        public Nullable<int> PPPF_PRY_ANO { get; set; }
        public Nullable<int> PPPF_PRY_TIT { get; set; }
        public Nullable<int> PPPF_PRY_QTY_FAM { get; set; }
        public Nullable<int> PPPF_PRY_TIP { get; set; }
        public Nullable<int> PPPF_PSAT_RUT { get; set; }
        public Nullable<int> REG_COD { get; set; }
        public Nullable<int> PRV_COD { get; set; }
        public Nullable<int> COM_COD { get; set; }
        public Nullable<int> PPPF_NUM_LLAM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WEB_ASISTEC_SNATIII_PPPF_CONTRATO_PROYECTO> WEB_ASISTEC_SNATIII_PPPF_CONTRATO_PROYECTO { get; set; }
    }
}
