//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_ASISTEC_SNATIII_PPPF_CONTRATO_PROYECTO
    {
        public int PPPF_CTO_PRY_ID { get; set; }
        public Nullable<int> PPPF_CTO_ID { get; set; }
        public Nullable<int> PPPF_PRY_ID { get; set; }
        public Nullable<int> PPPF_CTO_RUT_PROF { get; set; }
        public Nullable<int> PPPF_CTO_RUT_PROF_RMPLZ { get; set; }
        public Nullable<int> PPPF_CTO_RUT_SERVIU { get; set; }
        public Nullable<int> PPPF_CTO_RUT_SERVIU_RMPLZ { get; set; }
        public Nullable<int> PPPF_CTO_RUT_SPV { get; set; }
        public Nullable<int> PPPF_CTO_RUT_SPV_RMPLZ { get; set; }
    
        public virtual WEB_ASISTEC_SNATIII_PPPF_PROYECTO WEB_ASISTEC_SNATIII_PPPF_PROYECTO { get; set; }
    }
}
