//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_ASISTEC_SNATIII_PROFESIONALES
    {
        public int PROF_RUT { get; set; }
        public int PROF_PROF_ID { get; set; }
        public int PROF_EST { get; set; }
        public string PROF_DGV { get; set; }
        public string PROF_NOM { get; set; }
        public string PROF_APP_PAT { get; set; }
        public string PROF_APP_MAT { get; set; }
        public Nullable<int> PROF_ITO { get; set; }
    
        public virtual WEB_ASISTEC_SNATIII_PROFESION WEB_ASISTEC_SNATIII_PROFESION { get; set; }
    }
}
