//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.Domain.IconService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IconService.WsGarantiasSoap")]
    public interface WsGarantiasSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento RUTT del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consulta_boletas_reconstruccion", ReplyAction="*")]
        Minvu.Snat.Domain.IconService.consulta_boletas_reconstruccionResponse consulta_boletas_reconstruccion(Minvu.Snat.Domain.IconService.consulta_boletas_reconstruccionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consulta_boletas_reconstruccion", ReplyAction="*")]
        System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.consulta_boletas_reconstruccionResponse> consulta_boletas_reconstruccionAsync(Minvu.Snat.Domain.IconService.consulta_boletas_reconstruccionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento RUTT del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consulta_boletas", ReplyAction="*")]
        Minvu.Snat.Domain.IconService.consulta_boletasResponse consulta_boletas(Minvu.Snat.Domain.IconService.consulta_boletasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consulta_boletas", ReplyAction="*")]
        System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.consulta_boletasResponse> consulta_boletasAsync(Minvu.Snat.Domain.IconService.consulta_boletasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento RUTT del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consulta_boletas_SOE", ReplyAction="*")]
        Minvu.Snat.Domain.IconService.consulta_boletas_SOEResponse consulta_boletas_SOE(Minvu.Snat.Domain.IconService.consulta_boletas_SOERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consulta_boletas_SOE", ReplyAction="*")]
        System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.consulta_boletas_SOEResponse> consulta_boletas_SOEAsync(Minvu.Snat.Domain.IconService.consulta_boletas_SOERequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento EMP del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inserta_Garantias", ReplyAction="*")]
        Minvu.Snat.Domain.IconService.Inserta_GarantiasResponse Inserta_Garantias(Minvu.Snat.Domain.IconService.Inserta_GarantiasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inserta_Garantias", ReplyAction="*")]
        System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.Inserta_GarantiasResponse> Inserta_GarantiasAsync(Minvu.Snat.Domain.IconService.Inserta_GarantiasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento FECHA del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modifica_Fecha_Vencimiento", ReplyAction="*")]
        Minvu.Snat.Domain.IconService.Modifica_Fecha_VencimientoResponse Modifica_Fecha_Vencimiento(Minvu.Snat.Domain.IconService.Modifica_Fecha_VencimientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modifica_Fecha_Vencimiento", ReplyAction="*")]
        System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.Modifica_Fecha_VencimientoResponse> Modifica_Fecha_VencimientoAsync(Minvu.Snat.Domain.IconService.Modifica_Fecha_VencimientoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cf del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consulta_boletas_proyecto", ReplyAction="*")]
        Minvu.Snat.Domain.IconService.consulta_boletas_proyectoResponse consulta_boletas_proyecto(Minvu.Snat.Domain.IconService.consulta_boletas_proyectoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consulta_boletas_proyecto", ReplyAction="*")]
        System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.consulta_boletas_proyectoResponse> consulta_boletas_proyectoAsync(Minvu.Snat.Domain.IconService.consulta_boletas_proyectoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cf del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consulta_boletas_SNAT", ReplyAction="*")]
        Minvu.Snat.Domain.IconService.consulta_boletas_SNATResponse consulta_boletas_SNAT(Minvu.Snat.Domain.IconService.consulta_boletas_SNATRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consulta_boletas_SNAT", ReplyAction="*")]
        System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.consulta_boletas_SNATResponse> consulta_boletas_SNATAsync(Minvu.Snat.Domain.IconService.consulta_boletas_SNATRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento vfolio del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consulta_boletas_mm", ReplyAction="*")]
        Minvu.Snat.Domain.IconService.consulta_boletas_mmResponse consulta_boletas_mm(Minvu.Snat.Domain.IconService.consulta_boletas_mmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consulta_boletas_mm", ReplyAction="*")]
        System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.consulta_boletas_mmResponse> consulta_boletas_mmAsync(Minvu.Snat.Domain.IconService.consulta_boletas_mmRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cf del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta_Boletas_Proyecto_y_folio", ReplyAction="*")]
        Minvu.Snat.Domain.IconService.Consulta_Boletas_Proyecto_y_folioResponse Consulta_Boletas_Proyecto_y_folio(Minvu.Snat.Domain.IconService.Consulta_Boletas_Proyecto_y_folioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta_Boletas_Proyecto_y_folio", ReplyAction="*")]
        System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.Consulta_Boletas_Proyecto_y_folioResponse> Consulta_Boletas_Proyecto_y_folioAsync(Minvu.Snat.Domain.IconService.Consulta_Boletas_Proyecto_y_folioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento empresa del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registros_sps", ReplyAction="*")]
        Minvu.Snat.Domain.IconService.registros_spsResponse registros_sps(Minvu.Snat.Domain.IconService.registros_spsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registros_sps", ReplyAction="*")]
        System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.registros_spsResponse> registros_spsAsync(Minvu.Snat.Domain.IconService.registros_spsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consulta_boletas_reconstruccionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consulta_boletas_reconstruccion", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.Snat.Domain.IconService.consulta_boletas_reconstruccionRequestBody Body;
        
        public consulta_boletas_reconstruccionRequest() {
        }
        
        public consulta_boletas_reconstruccionRequest(Minvu.Snat.Domain.IconService.consulta_boletas_reconstruccionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consulta_boletas_reconstruccionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RUTT;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DV;
        
        public consulta_boletas_reconstruccionRequestBody() {
        }
        
        public consulta_boletas_reconstruccionRequestBody(string RUTT, string DV) {
            this.RUTT = RUTT;
            this.DV = DV;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consulta_boletas_reconstruccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consulta_boletas_reconstruccionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.Snat.Domain.IconService.consulta_boletas_reconstruccionResponseBody Body;
        
        public consulta_boletas_reconstruccionResponse() {
        }
        
        public consulta_boletas_reconstruccionResponse(Minvu.Snat.Domain.IconService.consulta_boletas_reconstruccionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consulta_boletas_reconstruccionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string consulta_boletas_reconstruccionResult;
        
        public consulta_boletas_reconstruccionResponseBody() {
        }
        
        public consulta_boletas_reconstruccionResponseBody(string consulta_boletas_reconstruccionResult) {
            this.consulta_boletas_reconstruccionResult = consulta_boletas_reconstruccionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consulta_boletasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consulta_boletas", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.Snat.Domain.IconService.consulta_boletasRequestBody Body;
        
        public consulta_boletasRequest() {
        }
        
        public consulta_boletasRequest(Minvu.Snat.Domain.IconService.consulta_boletasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consulta_boletasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RUTT;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DV;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NUMERO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FOLIO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string USUARIO;
        
        public consulta_boletasRequestBody() {
        }
        
        public consulta_boletasRequestBody(string RUTT, string DV, string NUMERO, string FOLIO, string USUARIO) {
            this.RUTT = RUTT;
            this.DV = DV;
            this.NUMERO = NUMERO;
            this.FOLIO = FOLIO;
            this.USUARIO = USUARIO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consulta_boletasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consulta_boletasResponse", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.Snat.Domain.IconService.consulta_boletasResponseBody Body;
        
        public consulta_boletasResponse() {
        }
        
        public consulta_boletasResponse(Minvu.Snat.Domain.IconService.consulta_boletasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consulta_boletasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string consulta_boletasResult;
        
        public consulta_boletasResponseBody() {
        }
        
        public consulta_boletasResponseBody(string consulta_boletasResult) {
            this.consulta_boletasResult = consulta_boletasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consulta_boletas_SOERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consulta_boletas_SOE", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.Snat.Domain.IconService.consulta_boletas_SOERequestBody Body;
        
        public consulta_boletas_SOERequest() {
        }
        
        public consulta_boletas_SOERequest(Minvu.Snat.Domain.IconService.consulta_boletas_SOERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consulta_boletas_SOERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RUTT;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DV;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NUMERO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FOLIO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string USUARIO;
        
        public consulta_boletas_SOERequestBody() {
        }
        
        public consulta_boletas_SOERequestBody(string RUTT, string DV, string NUMERO, string FOLIO, string USUARIO) {
            this.RUTT = RUTT;
            this.DV = DV;
            this.NUMERO = NUMERO;
            this.FOLIO = FOLIO;
            this.USUARIO = USUARIO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consulta_boletas_SOEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consulta_boletas_SOEResponse", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.Snat.Domain.IconService.consulta_boletas_SOEResponseBody Body;
        
        public consulta_boletas_SOEResponse() {
        }
        
        public consulta_boletas_SOEResponse(Minvu.Snat.Domain.IconService.consulta_boletas_SOEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consulta_boletas_SOEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string consulta_boletas_SOEResult;
        
        public consulta_boletas_SOEResponseBody() {
        }
        
        public consulta_boletas_SOEResponseBody(string consulta_boletas_SOEResult) {
            this.consulta_boletas_SOEResult = consulta_boletas_SOEResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Inserta_GarantiasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Inserta_Garantias", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.Snat.Domain.IconService.Inserta_GarantiasRequestBody Body;
        
        public Inserta_GarantiasRequest() {
        }
        
        public Inserta_GarantiasRequest(Minvu.Snat.Domain.IconService.Inserta_GarantiasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Inserta_GarantiasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EMP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string T_DOC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string OBJ;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string C_COSTO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string F_INI;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string F_TER;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string RUT_T;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string DV_T;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string DOC_REF;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string NOM_TOM;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string OC_REF;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string FEC_REF;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string MONEDA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string OR_MONTO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string V_CAMBIO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string GLOSA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string F_PRESE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string NOM_FAVOR;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string RUT_FAVOR;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string USUARIO;
        
        public Inserta_GarantiasRequestBody() {
        }
        
        public Inserta_GarantiasRequestBody(
                    string EMP, 
                    string T_DOC, 
                    string OBJ, 
                    string C_COSTO, 
                    string F_INI, 
                    string F_TER, 
                    string RUT_T, 
                    string DV_T, 
                    string DOC_REF, 
                    string NOM_TOM, 
                    string OC_REF, 
                    string FEC_REF, 
                    string MONEDA, 
                    string OR_MONTO, 
                    string V_CAMBIO, 
                    string GLOSA, 
                    string F_PRESE, 
                    string NOM_FAVOR, 
                    string RUT_FAVOR, 
                    string USUARIO) {
            this.EMP = EMP;
            this.T_DOC = T_DOC;
            this.OBJ = OBJ;
            this.C_COSTO = C_COSTO;
            this.F_INI = F_INI;
            this.F_TER = F_TER;
            this.RUT_T = RUT_T;
            this.DV_T = DV_T;
            this.DOC_REF = DOC_REF;
            this.NOM_TOM = NOM_TOM;
            this.OC_REF = OC_REF;
            this.FEC_REF = FEC_REF;
            this.MONEDA = MONEDA;
            this.OR_MONTO = OR_MONTO;
            this.V_CAMBIO = V_CAMBIO;
            this.GLOSA = GLOSA;
            this.F_PRESE = F_PRESE;
            this.NOM_FAVOR = NOM_FAVOR;
            this.RUT_FAVOR = RUT_FAVOR;
            this.USUARIO = USUARIO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Inserta_GarantiasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Inserta_GarantiasResponse", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.Snat.Domain.IconService.Inserta_GarantiasResponseBody Body;
        
        public Inserta_GarantiasResponse() {
        }
        
        public Inserta_GarantiasResponse(Minvu.Snat.Domain.IconService.Inserta_GarantiasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Inserta_GarantiasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Inserta_GarantiasResult;
        
        public Inserta_GarantiasResponseBody() {
        }
        
        public Inserta_GarantiasResponseBody(string Inserta_GarantiasResult) {
            this.Inserta_GarantiasResult = Inserta_GarantiasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Modifica_Fecha_VencimientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Modifica_Fecha_Vencimiento", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.Snat.Domain.IconService.Modifica_Fecha_VencimientoRequestBody Body;
        
        public Modifica_Fecha_VencimientoRequest() {
        }
        
        public Modifica_Fecha_VencimientoRequest(Minvu.Snat.Domain.IconService.Modifica_Fecha_VencimientoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Modifica_Fecha_VencimientoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FECHA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FOLIO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string USUARIO;
        
        public Modifica_Fecha_VencimientoRequestBody() {
        }
        
        public Modifica_Fecha_VencimientoRequestBody(string FECHA, string FOLIO, string USUARIO) {
            this.FECHA = FECHA;
            this.FOLIO = FOLIO;
            this.USUARIO = USUARIO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Modifica_Fecha_VencimientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Modifica_Fecha_VencimientoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.Snat.Domain.IconService.Modifica_Fecha_VencimientoResponseBody Body;
        
        public Modifica_Fecha_VencimientoResponse() {
        }
        
        public Modifica_Fecha_VencimientoResponse(Minvu.Snat.Domain.IconService.Modifica_Fecha_VencimientoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Modifica_Fecha_VencimientoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Modifica_Fecha_VencimientoResult;
        
        public Modifica_Fecha_VencimientoResponseBody() {
        }
        
        public Modifica_Fecha_VencimientoResponseBody(string Modifica_Fecha_VencimientoResult) {
            this.Modifica_Fecha_VencimientoResult = Modifica_Fecha_VencimientoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consulta_boletas_proyectoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consulta_boletas_proyecto", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.Snat.Domain.IconService.consulta_boletas_proyectoRequestBody Body;
        
        public consulta_boletas_proyectoRequest() {
        }
        
        public consulta_boletas_proyectoRequest(Minvu.Snat.Domain.IconService.consulta_boletas_proyectoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consulta_boletas_proyectoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cf;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tipocontratista;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tipoprograma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string codigopry;
        
        public consulta_boletas_proyectoRequestBody() {
        }
        
        public consulta_boletas_proyectoRequestBody(string cf, string tipocontratista, string tipoprograma, string codigopry) {
            this.cf = cf;
            this.tipocontratista = tipocontratista;
            this.tipoprograma = tipoprograma;
            this.codigopry = codigopry;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consulta_boletas_proyectoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consulta_boletas_proyectoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.Snat.Domain.IconService.consulta_boletas_proyectoResponseBody Body;
        
        public consulta_boletas_proyectoResponse() {
        }
        
        public consulta_boletas_proyectoResponse(Minvu.Snat.Domain.IconService.consulta_boletas_proyectoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consulta_boletas_proyectoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string consulta_boletas_proyectoResult;
        
        public consulta_boletas_proyectoResponseBody() {
        }
        
        public consulta_boletas_proyectoResponseBody(string consulta_boletas_proyectoResult) {
            this.consulta_boletas_proyectoResult = consulta_boletas_proyectoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consulta_boletas_SNATRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consulta_boletas_SNAT", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.Snat.Domain.IconService.consulta_boletas_SNATRequestBody Body;
        
        public consulta_boletas_SNATRequest() {
        }
        
        public consulta_boletas_SNATRequest(Minvu.Snat.Domain.IconService.consulta_boletas_SNATRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consulta_boletas_SNATRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cf;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tipocontratista;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tipoprograma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string codigopry;
        
        public consulta_boletas_SNATRequestBody() {
        }
        
        public consulta_boletas_SNATRequestBody(string cf, string tipocontratista, string tipoprograma, string codigopry) {
            this.cf = cf;
            this.tipocontratista = tipocontratista;
            this.tipoprograma = tipoprograma;
            this.codigopry = codigopry;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consulta_boletas_SNATResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consulta_boletas_SNATResponse", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.Snat.Domain.IconService.consulta_boletas_SNATResponseBody Body;
        
        public consulta_boletas_SNATResponse() {
        }
        
        public consulta_boletas_SNATResponse(Minvu.Snat.Domain.IconService.consulta_boletas_SNATResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consulta_boletas_SNATResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string consulta_boletas_SNATResult;
        
        public consulta_boletas_SNATResponseBody() {
        }
        
        public consulta_boletas_SNATResponseBody(string consulta_boletas_SNATResult) {
            this.consulta_boletas_SNATResult = consulta_boletas_SNATResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consulta_boletas_mmRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consulta_boletas_mm", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.Snat.Domain.IconService.consulta_boletas_mmRequestBody Body;
        
        public consulta_boletas_mmRequest() {
        }
        
        public consulta_boletas_mmRequest(Minvu.Snat.Domain.IconService.consulta_boletas_mmRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consulta_boletas_mmRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string vfolio;
        
        public consulta_boletas_mmRequestBody() {
        }
        
        public consulta_boletas_mmRequestBody(string vfolio) {
            this.vfolio = vfolio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consulta_boletas_mmResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consulta_boletas_mmResponse", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.Snat.Domain.IconService.consulta_boletas_mmResponseBody Body;
        
        public consulta_boletas_mmResponse() {
        }
        
        public consulta_boletas_mmResponse(Minvu.Snat.Domain.IconService.consulta_boletas_mmResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consulta_boletas_mmResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string consulta_boletas_mmResult;
        
        public consulta_boletas_mmResponseBody() {
        }
        
        public consulta_boletas_mmResponseBody(string consulta_boletas_mmResult) {
            this.consulta_boletas_mmResult = consulta_boletas_mmResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Consulta_Boletas_Proyecto_y_folioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consulta_Boletas_Proyecto_y_folio", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.Snat.Domain.IconService.Consulta_Boletas_Proyecto_y_folioRequestBody Body;
        
        public Consulta_Boletas_Proyecto_y_folioRequest() {
        }
        
        public Consulta_Boletas_Proyecto_y_folioRequest(Minvu.Snat.Domain.IconService.Consulta_Boletas_Proyecto_y_folioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Consulta_Boletas_Proyecto_y_folioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cf;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nfolio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string codigopry;
        
        public Consulta_Boletas_Proyecto_y_folioRequestBody() {
        }
        
        public Consulta_Boletas_Proyecto_y_folioRequestBody(string cf, string nfolio, string codigopry) {
            this.cf = cf;
            this.nfolio = nfolio;
            this.codigopry = codigopry;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Consulta_Boletas_Proyecto_y_folioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consulta_Boletas_Proyecto_y_folioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.Snat.Domain.IconService.Consulta_Boletas_Proyecto_y_folioResponseBody Body;
        
        public Consulta_Boletas_Proyecto_y_folioResponse() {
        }
        
        public Consulta_Boletas_Proyecto_y_folioResponse(Minvu.Snat.Domain.IconService.Consulta_Boletas_Proyecto_y_folioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Consulta_Boletas_Proyecto_y_folioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Consulta_Boletas_Proyecto_y_folioResult;
        
        public Consulta_Boletas_Proyecto_y_folioResponseBody() {
        }
        
        public Consulta_Boletas_Proyecto_y_folioResponseBody(string Consulta_Boletas_Proyecto_y_folioResult) {
            this.Consulta_Boletas_Proyecto_y_folioResult = Consulta_Boletas_Proyecto_y_folioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registros_spsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registros_sps", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.Snat.Domain.IconService.registros_spsRequestBody Body;
        
        public registros_spsRequest() {
        }
        
        public registros_spsRequest(Minvu.Snat.Domain.IconService.registros_spsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registros_spsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string empresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string codigo_depto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string centro_costo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string rut_proveedor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string rut_pagador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string tipo_docto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string nro_docto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string cantidad_reg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string fecha_registro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string monto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string p_corr_preoblig;
        
        public registros_spsRequestBody() {
        }
        
        public registros_spsRequestBody(string empresa, string codigo_depto, string centro_costo, string rut_proveedor, string rut_pagador, string tipo_docto, string nro_docto, string cantidad_reg, string fecha_registro, string monto, string p_corr_preoblig) {
            this.empresa = empresa;
            this.codigo_depto = codigo_depto;
            this.centro_costo = centro_costo;
            this.rut_proveedor = rut_proveedor;
            this.rut_pagador = rut_pagador;
            this.tipo_docto = tipo_docto;
            this.nro_docto = nro_docto;
            this.cantidad_reg = cantidad_reg;
            this.fecha_registro = fecha_registro;
            this.monto = monto;
            this.p_corr_preoblig = p_corr_preoblig;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registros_spsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registros_spsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.Snat.Domain.IconService.registros_spsResponseBody Body;
        
        public registros_spsResponse() {
        }
        
        public registros_spsResponse(Minvu.Snat.Domain.IconService.registros_spsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registros_spsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string registros_spsResult;
        
        public registros_spsResponseBody() {
        }
        
        public registros_spsResponseBody(string registros_spsResult) {
            this.registros_spsResult = registros_spsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsGarantiasSoapChannel : Minvu.Snat.Domain.IconService.WsGarantiasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsGarantiasSoapClient : System.ServiceModel.ClientBase<Minvu.Snat.Domain.IconService.WsGarantiasSoap>, Minvu.Snat.Domain.IconService.WsGarantiasSoap {
        
        public WsGarantiasSoapClient() {
        }
        
        public WsGarantiasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsGarantiasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsGarantiasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsGarantiasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Minvu.Snat.Domain.IconService.consulta_boletas_reconstruccionResponse Minvu.Snat.Domain.IconService.WsGarantiasSoap.consulta_boletas_reconstruccion(Minvu.Snat.Domain.IconService.consulta_boletas_reconstruccionRequest request) {
            return base.Channel.consulta_boletas_reconstruccion(request);
        }
        
        public string consulta_boletas_reconstruccion(string RUTT, string DV) {
            Minvu.Snat.Domain.IconService.consulta_boletas_reconstruccionRequest inValue = new Minvu.Snat.Domain.IconService.consulta_boletas_reconstruccionRequest();
            inValue.Body = new Minvu.Snat.Domain.IconService.consulta_boletas_reconstruccionRequestBody();
            inValue.Body.RUTT = RUTT;
            inValue.Body.DV = DV;
            Minvu.Snat.Domain.IconService.consulta_boletas_reconstruccionResponse retVal = ((Minvu.Snat.Domain.IconService.WsGarantiasSoap)(this)).consulta_boletas_reconstruccion(inValue);
            return retVal.Body.consulta_boletas_reconstruccionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.consulta_boletas_reconstruccionResponse> Minvu.Snat.Domain.IconService.WsGarantiasSoap.consulta_boletas_reconstruccionAsync(Minvu.Snat.Domain.IconService.consulta_boletas_reconstruccionRequest request) {
            return base.Channel.consulta_boletas_reconstruccionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.consulta_boletas_reconstruccionResponse> consulta_boletas_reconstruccionAsync(string RUTT, string DV) {
            Minvu.Snat.Domain.IconService.consulta_boletas_reconstruccionRequest inValue = new Minvu.Snat.Domain.IconService.consulta_boletas_reconstruccionRequest();
            inValue.Body = new Minvu.Snat.Domain.IconService.consulta_boletas_reconstruccionRequestBody();
            inValue.Body.RUTT = RUTT;
            inValue.Body.DV = DV;
            return ((Minvu.Snat.Domain.IconService.WsGarantiasSoap)(this)).consulta_boletas_reconstruccionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Minvu.Snat.Domain.IconService.consulta_boletasResponse Minvu.Snat.Domain.IconService.WsGarantiasSoap.consulta_boletas(Minvu.Snat.Domain.IconService.consulta_boletasRequest request) {
            return base.Channel.consulta_boletas(request);
        }
        
        public string consulta_boletas(string RUTT, string DV, string NUMERO, string FOLIO, string USUARIO) {
            Minvu.Snat.Domain.IconService.consulta_boletasRequest inValue = new Minvu.Snat.Domain.IconService.consulta_boletasRequest();
            inValue.Body = new Minvu.Snat.Domain.IconService.consulta_boletasRequestBody();
            inValue.Body.RUTT = RUTT;
            inValue.Body.DV = DV;
            inValue.Body.NUMERO = NUMERO;
            inValue.Body.FOLIO = FOLIO;
            inValue.Body.USUARIO = USUARIO;
            Minvu.Snat.Domain.IconService.consulta_boletasResponse retVal = ((Minvu.Snat.Domain.IconService.WsGarantiasSoap)(this)).consulta_boletas(inValue);
            return retVal.Body.consulta_boletasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.consulta_boletasResponse> Minvu.Snat.Domain.IconService.WsGarantiasSoap.consulta_boletasAsync(Minvu.Snat.Domain.IconService.consulta_boletasRequest request) {
            return base.Channel.consulta_boletasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.consulta_boletasResponse> consulta_boletasAsync(string RUTT, string DV, string NUMERO, string FOLIO, string USUARIO) {
            Minvu.Snat.Domain.IconService.consulta_boletasRequest inValue = new Minvu.Snat.Domain.IconService.consulta_boletasRequest();
            inValue.Body = new Minvu.Snat.Domain.IconService.consulta_boletasRequestBody();
            inValue.Body.RUTT = RUTT;
            inValue.Body.DV = DV;
            inValue.Body.NUMERO = NUMERO;
            inValue.Body.FOLIO = FOLIO;
            inValue.Body.USUARIO = USUARIO;
            return ((Minvu.Snat.Domain.IconService.WsGarantiasSoap)(this)).consulta_boletasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Minvu.Snat.Domain.IconService.consulta_boletas_SOEResponse Minvu.Snat.Domain.IconService.WsGarantiasSoap.consulta_boletas_SOE(Minvu.Snat.Domain.IconService.consulta_boletas_SOERequest request) {
            return base.Channel.consulta_boletas_SOE(request);
        }
        
        public string consulta_boletas_SOE(string RUTT, string DV, string NUMERO, string FOLIO, string USUARIO) {
            Minvu.Snat.Domain.IconService.consulta_boletas_SOERequest inValue = new Minvu.Snat.Domain.IconService.consulta_boletas_SOERequest();
            inValue.Body = new Minvu.Snat.Domain.IconService.consulta_boletas_SOERequestBody();
            inValue.Body.RUTT = RUTT;
            inValue.Body.DV = DV;
            inValue.Body.NUMERO = NUMERO;
            inValue.Body.FOLIO = FOLIO;
            inValue.Body.USUARIO = USUARIO;
            Minvu.Snat.Domain.IconService.consulta_boletas_SOEResponse retVal = ((Minvu.Snat.Domain.IconService.WsGarantiasSoap)(this)).consulta_boletas_SOE(inValue);
            return retVal.Body.consulta_boletas_SOEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.consulta_boletas_SOEResponse> Minvu.Snat.Domain.IconService.WsGarantiasSoap.consulta_boletas_SOEAsync(Minvu.Snat.Domain.IconService.consulta_boletas_SOERequest request) {
            return base.Channel.consulta_boletas_SOEAsync(request);
        }
        
        public System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.consulta_boletas_SOEResponse> consulta_boletas_SOEAsync(string RUTT, string DV, string NUMERO, string FOLIO, string USUARIO) {
            Minvu.Snat.Domain.IconService.consulta_boletas_SOERequest inValue = new Minvu.Snat.Domain.IconService.consulta_boletas_SOERequest();
            inValue.Body = new Minvu.Snat.Domain.IconService.consulta_boletas_SOERequestBody();
            inValue.Body.RUTT = RUTT;
            inValue.Body.DV = DV;
            inValue.Body.NUMERO = NUMERO;
            inValue.Body.FOLIO = FOLIO;
            inValue.Body.USUARIO = USUARIO;
            return ((Minvu.Snat.Domain.IconService.WsGarantiasSoap)(this)).consulta_boletas_SOEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Minvu.Snat.Domain.IconService.Inserta_GarantiasResponse Minvu.Snat.Domain.IconService.WsGarantiasSoap.Inserta_Garantias(Minvu.Snat.Domain.IconService.Inserta_GarantiasRequest request) {
            return base.Channel.Inserta_Garantias(request);
        }
        
        public string Inserta_Garantias(
                    string EMP, 
                    string T_DOC, 
                    string OBJ, 
                    string C_COSTO, 
                    string F_INI, 
                    string F_TER, 
                    string RUT_T, 
                    string DV_T, 
                    string DOC_REF, 
                    string NOM_TOM, 
                    string OC_REF, 
                    string FEC_REF, 
                    string MONEDA, 
                    string OR_MONTO, 
                    string V_CAMBIO, 
                    string GLOSA, 
                    string F_PRESE, 
                    string NOM_FAVOR, 
                    string RUT_FAVOR, 
                    string USUARIO) {
            Minvu.Snat.Domain.IconService.Inserta_GarantiasRequest inValue = new Minvu.Snat.Domain.IconService.Inserta_GarantiasRequest();
            inValue.Body = new Minvu.Snat.Domain.IconService.Inserta_GarantiasRequestBody();
            inValue.Body.EMP = EMP;
            inValue.Body.T_DOC = T_DOC;
            inValue.Body.OBJ = OBJ;
            inValue.Body.C_COSTO = C_COSTO;
            inValue.Body.F_INI = F_INI;
            inValue.Body.F_TER = F_TER;
            inValue.Body.RUT_T = RUT_T;
            inValue.Body.DV_T = DV_T;
            inValue.Body.DOC_REF = DOC_REF;
            inValue.Body.NOM_TOM = NOM_TOM;
            inValue.Body.OC_REF = OC_REF;
            inValue.Body.FEC_REF = FEC_REF;
            inValue.Body.MONEDA = MONEDA;
            inValue.Body.OR_MONTO = OR_MONTO;
            inValue.Body.V_CAMBIO = V_CAMBIO;
            inValue.Body.GLOSA = GLOSA;
            inValue.Body.F_PRESE = F_PRESE;
            inValue.Body.NOM_FAVOR = NOM_FAVOR;
            inValue.Body.RUT_FAVOR = RUT_FAVOR;
            inValue.Body.USUARIO = USUARIO;
            Minvu.Snat.Domain.IconService.Inserta_GarantiasResponse retVal = ((Minvu.Snat.Domain.IconService.WsGarantiasSoap)(this)).Inserta_Garantias(inValue);
            return retVal.Body.Inserta_GarantiasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.Inserta_GarantiasResponse> Minvu.Snat.Domain.IconService.WsGarantiasSoap.Inserta_GarantiasAsync(Minvu.Snat.Domain.IconService.Inserta_GarantiasRequest request) {
            return base.Channel.Inserta_GarantiasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.Inserta_GarantiasResponse> Inserta_GarantiasAsync(
                    string EMP, 
                    string T_DOC, 
                    string OBJ, 
                    string C_COSTO, 
                    string F_INI, 
                    string F_TER, 
                    string RUT_T, 
                    string DV_T, 
                    string DOC_REF, 
                    string NOM_TOM, 
                    string OC_REF, 
                    string FEC_REF, 
                    string MONEDA, 
                    string OR_MONTO, 
                    string V_CAMBIO, 
                    string GLOSA, 
                    string F_PRESE, 
                    string NOM_FAVOR, 
                    string RUT_FAVOR, 
                    string USUARIO) {
            Minvu.Snat.Domain.IconService.Inserta_GarantiasRequest inValue = new Minvu.Snat.Domain.IconService.Inserta_GarantiasRequest();
            inValue.Body = new Minvu.Snat.Domain.IconService.Inserta_GarantiasRequestBody();
            inValue.Body.EMP = EMP;
            inValue.Body.T_DOC = T_DOC;
            inValue.Body.OBJ = OBJ;
            inValue.Body.C_COSTO = C_COSTO;
            inValue.Body.F_INI = F_INI;
            inValue.Body.F_TER = F_TER;
            inValue.Body.RUT_T = RUT_T;
            inValue.Body.DV_T = DV_T;
            inValue.Body.DOC_REF = DOC_REF;
            inValue.Body.NOM_TOM = NOM_TOM;
            inValue.Body.OC_REF = OC_REF;
            inValue.Body.FEC_REF = FEC_REF;
            inValue.Body.MONEDA = MONEDA;
            inValue.Body.OR_MONTO = OR_MONTO;
            inValue.Body.V_CAMBIO = V_CAMBIO;
            inValue.Body.GLOSA = GLOSA;
            inValue.Body.F_PRESE = F_PRESE;
            inValue.Body.NOM_FAVOR = NOM_FAVOR;
            inValue.Body.RUT_FAVOR = RUT_FAVOR;
            inValue.Body.USUARIO = USUARIO;
            return ((Minvu.Snat.Domain.IconService.WsGarantiasSoap)(this)).Inserta_GarantiasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Minvu.Snat.Domain.IconService.Modifica_Fecha_VencimientoResponse Minvu.Snat.Domain.IconService.WsGarantiasSoap.Modifica_Fecha_Vencimiento(Minvu.Snat.Domain.IconService.Modifica_Fecha_VencimientoRequest request) {
            return base.Channel.Modifica_Fecha_Vencimiento(request);
        }
        
        public string Modifica_Fecha_Vencimiento(string FECHA, string FOLIO, string USUARIO) {
            Minvu.Snat.Domain.IconService.Modifica_Fecha_VencimientoRequest inValue = new Minvu.Snat.Domain.IconService.Modifica_Fecha_VencimientoRequest();
            inValue.Body = new Minvu.Snat.Domain.IconService.Modifica_Fecha_VencimientoRequestBody();
            inValue.Body.FECHA = FECHA;
            inValue.Body.FOLIO = FOLIO;
            inValue.Body.USUARIO = USUARIO;
            Minvu.Snat.Domain.IconService.Modifica_Fecha_VencimientoResponse retVal = ((Minvu.Snat.Domain.IconService.WsGarantiasSoap)(this)).Modifica_Fecha_Vencimiento(inValue);
            return retVal.Body.Modifica_Fecha_VencimientoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.Modifica_Fecha_VencimientoResponse> Minvu.Snat.Domain.IconService.WsGarantiasSoap.Modifica_Fecha_VencimientoAsync(Minvu.Snat.Domain.IconService.Modifica_Fecha_VencimientoRequest request) {
            return base.Channel.Modifica_Fecha_VencimientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.Modifica_Fecha_VencimientoResponse> Modifica_Fecha_VencimientoAsync(string FECHA, string FOLIO, string USUARIO) {
            Minvu.Snat.Domain.IconService.Modifica_Fecha_VencimientoRequest inValue = new Minvu.Snat.Domain.IconService.Modifica_Fecha_VencimientoRequest();
            inValue.Body = new Minvu.Snat.Domain.IconService.Modifica_Fecha_VencimientoRequestBody();
            inValue.Body.FECHA = FECHA;
            inValue.Body.FOLIO = FOLIO;
            inValue.Body.USUARIO = USUARIO;
            return ((Minvu.Snat.Domain.IconService.WsGarantiasSoap)(this)).Modifica_Fecha_VencimientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Minvu.Snat.Domain.IconService.consulta_boletas_proyectoResponse Minvu.Snat.Domain.IconService.WsGarantiasSoap.consulta_boletas_proyecto(Minvu.Snat.Domain.IconService.consulta_boletas_proyectoRequest request) {
            return base.Channel.consulta_boletas_proyecto(request);
        }
        
        public string consulta_boletas_proyecto(string cf, string tipocontratista, string tipoprograma, string codigopry) {
            Minvu.Snat.Domain.IconService.consulta_boletas_proyectoRequest inValue = new Minvu.Snat.Domain.IconService.consulta_boletas_proyectoRequest();
            inValue.Body = new Minvu.Snat.Domain.IconService.consulta_boletas_proyectoRequestBody();
            inValue.Body.cf = cf;
            inValue.Body.tipocontratista = tipocontratista;
            inValue.Body.tipoprograma = tipoprograma;
            inValue.Body.codigopry = codigopry;
            Minvu.Snat.Domain.IconService.consulta_boletas_proyectoResponse retVal = ((Minvu.Snat.Domain.IconService.WsGarantiasSoap)(this)).consulta_boletas_proyecto(inValue);
            return retVal.Body.consulta_boletas_proyectoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.consulta_boletas_proyectoResponse> Minvu.Snat.Domain.IconService.WsGarantiasSoap.consulta_boletas_proyectoAsync(Minvu.Snat.Domain.IconService.consulta_boletas_proyectoRequest request) {
            return base.Channel.consulta_boletas_proyectoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.consulta_boletas_proyectoResponse> consulta_boletas_proyectoAsync(string cf, string tipocontratista, string tipoprograma, string codigopry) {
            Minvu.Snat.Domain.IconService.consulta_boletas_proyectoRequest inValue = new Minvu.Snat.Domain.IconService.consulta_boletas_proyectoRequest();
            inValue.Body = new Minvu.Snat.Domain.IconService.consulta_boletas_proyectoRequestBody();
            inValue.Body.cf = cf;
            inValue.Body.tipocontratista = tipocontratista;
            inValue.Body.tipoprograma = tipoprograma;
            inValue.Body.codigopry = codigopry;
            return ((Minvu.Snat.Domain.IconService.WsGarantiasSoap)(this)).consulta_boletas_proyectoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Minvu.Snat.Domain.IconService.consulta_boletas_SNATResponse Minvu.Snat.Domain.IconService.WsGarantiasSoap.consulta_boletas_SNAT(Minvu.Snat.Domain.IconService.consulta_boletas_SNATRequest request) {
            return base.Channel.consulta_boletas_SNAT(request);
        }
        
        public string consulta_boletas_SNAT(string cf, string tipocontratista, string tipoprograma, string codigopry) {
            Minvu.Snat.Domain.IconService.consulta_boletas_SNATRequest inValue = new Minvu.Snat.Domain.IconService.consulta_boletas_SNATRequest();
            inValue.Body = new Minvu.Snat.Domain.IconService.consulta_boletas_SNATRequestBody();
            inValue.Body.cf = cf;
            inValue.Body.tipocontratista = tipocontratista;
            inValue.Body.tipoprograma = tipoprograma;
            inValue.Body.codigopry = codigopry;
            Minvu.Snat.Domain.IconService.consulta_boletas_SNATResponse retVal = ((Minvu.Snat.Domain.IconService.WsGarantiasSoap)(this)).consulta_boletas_SNAT(inValue);
            return retVal.Body.consulta_boletas_SNATResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.consulta_boletas_SNATResponse> Minvu.Snat.Domain.IconService.WsGarantiasSoap.consulta_boletas_SNATAsync(Minvu.Snat.Domain.IconService.consulta_boletas_SNATRequest request) {
            return base.Channel.consulta_boletas_SNATAsync(request);
        }
        
        public System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.consulta_boletas_SNATResponse> consulta_boletas_SNATAsync(string cf, string tipocontratista, string tipoprograma, string codigopry) {
            Minvu.Snat.Domain.IconService.consulta_boletas_SNATRequest inValue = new Minvu.Snat.Domain.IconService.consulta_boletas_SNATRequest();
            inValue.Body = new Minvu.Snat.Domain.IconService.consulta_boletas_SNATRequestBody();
            inValue.Body.cf = cf;
            inValue.Body.tipocontratista = tipocontratista;
            inValue.Body.tipoprograma = tipoprograma;
            inValue.Body.codigopry = codigopry;
            return ((Minvu.Snat.Domain.IconService.WsGarantiasSoap)(this)).consulta_boletas_SNATAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Minvu.Snat.Domain.IconService.consulta_boletas_mmResponse Minvu.Snat.Domain.IconService.WsGarantiasSoap.consulta_boletas_mm(Minvu.Snat.Domain.IconService.consulta_boletas_mmRequest request) {
            return base.Channel.consulta_boletas_mm(request);
        }
        
        public string consulta_boletas_mm(string vfolio) {
            Minvu.Snat.Domain.IconService.consulta_boletas_mmRequest inValue = new Minvu.Snat.Domain.IconService.consulta_boletas_mmRequest();
            inValue.Body = new Minvu.Snat.Domain.IconService.consulta_boletas_mmRequestBody();
            inValue.Body.vfolio = vfolio;
            Minvu.Snat.Domain.IconService.consulta_boletas_mmResponse retVal = ((Minvu.Snat.Domain.IconService.WsGarantiasSoap)(this)).consulta_boletas_mm(inValue);
            return retVal.Body.consulta_boletas_mmResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.consulta_boletas_mmResponse> Minvu.Snat.Domain.IconService.WsGarantiasSoap.consulta_boletas_mmAsync(Minvu.Snat.Domain.IconService.consulta_boletas_mmRequest request) {
            return base.Channel.consulta_boletas_mmAsync(request);
        }
        
        public System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.consulta_boletas_mmResponse> consulta_boletas_mmAsync(string vfolio) {
            Minvu.Snat.Domain.IconService.consulta_boletas_mmRequest inValue = new Minvu.Snat.Domain.IconService.consulta_boletas_mmRequest();
            inValue.Body = new Minvu.Snat.Domain.IconService.consulta_boletas_mmRequestBody();
            inValue.Body.vfolio = vfolio;
            return ((Minvu.Snat.Domain.IconService.WsGarantiasSoap)(this)).consulta_boletas_mmAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Minvu.Snat.Domain.IconService.Consulta_Boletas_Proyecto_y_folioResponse Minvu.Snat.Domain.IconService.WsGarantiasSoap.Consulta_Boletas_Proyecto_y_folio(Minvu.Snat.Domain.IconService.Consulta_Boletas_Proyecto_y_folioRequest request) {
            return base.Channel.Consulta_Boletas_Proyecto_y_folio(request);
        }
        
        public string Consulta_Boletas_Proyecto_y_folio(string cf, string nfolio, string codigopry) {
            Minvu.Snat.Domain.IconService.Consulta_Boletas_Proyecto_y_folioRequest inValue = new Minvu.Snat.Domain.IconService.Consulta_Boletas_Proyecto_y_folioRequest();
            inValue.Body = new Minvu.Snat.Domain.IconService.Consulta_Boletas_Proyecto_y_folioRequestBody();
            inValue.Body.cf = cf;
            inValue.Body.nfolio = nfolio;
            inValue.Body.codigopry = codigopry;
            Minvu.Snat.Domain.IconService.Consulta_Boletas_Proyecto_y_folioResponse retVal = ((Minvu.Snat.Domain.IconService.WsGarantiasSoap)(this)).Consulta_Boletas_Proyecto_y_folio(inValue);
            return retVal.Body.Consulta_Boletas_Proyecto_y_folioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.Consulta_Boletas_Proyecto_y_folioResponse> Minvu.Snat.Domain.IconService.WsGarantiasSoap.Consulta_Boletas_Proyecto_y_folioAsync(Minvu.Snat.Domain.IconService.Consulta_Boletas_Proyecto_y_folioRequest request) {
            return base.Channel.Consulta_Boletas_Proyecto_y_folioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.Consulta_Boletas_Proyecto_y_folioResponse> Consulta_Boletas_Proyecto_y_folioAsync(string cf, string nfolio, string codigopry) {
            Minvu.Snat.Domain.IconService.Consulta_Boletas_Proyecto_y_folioRequest inValue = new Minvu.Snat.Domain.IconService.Consulta_Boletas_Proyecto_y_folioRequest();
            inValue.Body = new Minvu.Snat.Domain.IconService.Consulta_Boletas_Proyecto_y_folioRequestBody();
            inValue.Body.cf = cf;
            inValue.Body.nfolio = nfolio;
            inValue.Body.codigopry = codigopry;
            return ((Minvu.Snat.Domain.IconService.WsGarantiasSoap)(this)).Consulta_Boletas_Proyecto_y_folioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Minvu.Snat.Domain.IconService.registros_spsResponse Minvu.Snat.Domain.IconService.WsGarantiasSoap.registros_sps(Minvu.Snat.Domain.IconService.registros_spsRequest request) {
            return base.Channel.registros_sps(request);
        }
        
        public string registros_sps(string empresa, string codigo_depto, string centro_costo, string rut_proveedor, string rut_pagador, string tipo_docto, string nro_docto, string cantidad_reg, string fecha_registro, string monto, string p_corr_preoblig) {
            Minvu.Snat.Domain.IconService.registros_spsRequest inValue = new Minvu.Snat.Domain.IconService.registros_spsRequest();
            inValue.Body = new Minvu.Snat.Domain.IconService.registros_spsRequestBody();
            inValue.Body.empresa = empresa;
            inValue.Body.codigo_depto = codigo_depto;
            inValue.Body.centro_costo = centro_costo;
            inValue.Body.rut_proveedor = rut_proveedor;
            inValue.Body.rut_pagador = rut_pagador;
            inValue.Body.tipo_docto = tipo_docto;
            inValue.Body.nro_docto = nro_docto;
            inValue.Body.cantidad_reg = cantidad_reg;
            inValue.Body.fecha_registro = fecha_registro;
            inValue.Body.monto = monto;
            inValue.Body.p_corr_preoblig = p_corr_preoblig;
            Minvu.Snat.Domain.IconService.registros_spsResponse retVal = ((Minvu.Snat.Domain.IconService.WsGarantiasSoap)(this)).registros_sps(inValue);
            return retVal.Body.registros_spsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.registros_spsResponse> Minvu.Snat.Domain.IconService.WsGarantiasSoap.registros_spsAsync(Minvu.Snat.Domain.IconService.registros_spsRequest request) {
            return base.Channel.registros_spsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Minvu.Snat.Domain.IconService.registros_spsResponse> registros_spsAsync(string empresa, string codigo_depto, string centro_costo, string rut_proveedor, string rut_pagador, string tipo_docto, string nro_docto, string cantidad_reg, string fecha_registro, string monto, string p_corr_preoblig) {
            Minvu.Snat.Domain.IconService.registros_spsRequest inValue = new Minvu.Snat.Domain.IconService.registros_spsRequest();
            inValue.Body = new Minvu.Snat.Domain.IconService.registros_spsRequestBody();
            inValue.Body.empresa = empresa;
            inValue.Body.codigo_depto = codigo_depto;
            inValue.Body.centro_costo = centro_costo;
            inValue.Body.rut_proveedor = rut_proveedor;
            inValue.Body.rut_pagador = rut_pagador;
            inValue.Body.tipo_docto = tipo_docto;
            inValue.Body.nro_docto = nro_docto;
            inValue.Body.cantidad_reg = cantidad_reg;
            inValue.Body.fecha_registro = fecha_registro;
            inValue.Body.monto = monto;
            inValue.Body.p_corr_preoblig = p_corr_preoblig;
            return ((Minvu.Snat.Domain.IconService.WsGarantiasSoap)(this)).registros_spsAsync(inValue);
        }
    }
}
