//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Snat.IData.SI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://minvu/ice/sii", ConfigurationName="SI.SII_orc_datcontrib_prt_sii_datcontribSoap")]
    public interface SII_orc_datcontrib_prt_sii_datcontribSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje (http://datcontrib.Schema_datcontrib_rice) no coincide con el valor predeterminado (http://minvu/ice/sii).
        [System.ServiceModel.OperationContractAttribute(Action="http://minvu/ice/sii/SII_orc_datcontrib_prt_sii_datcontrib/ope_prt_sii_datcontrib" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ICE")]
        Minvu.Snat.IData.SI.ope_prt_sii_datcontribResponse ope_prt_sii_datcontrib(Minvu.Snat.IData.SI.ope_prt_sii_datcontribRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://minvu/ice/sii/SII_orc_datcontrib_prt_sii_datcontrib/ope_prt_sii_datcontrib" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<Minvu.Snat.IData.SI.ope_prt_sii_datcontribResponse> ope_prt_sii_datcontribAsync(Minvu.Snat.IData.SI.ope_prt_sii_datcontribRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://SII.schemas.Schema_datcontrib_conice")]
    public partial class DatContrib : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rutField;
        
        private string dvField;
        
        private double periodoField;
        
        private string ussistField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Dv {
            get {
                return this.dvField;
            }
            set {
                this.dvField = value;
                this.RaisePropertyChanged("Dv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double Periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("Periodo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Ussist {
            get {
                return this.ussistField;
            }
            set {
                this.ussistField = value;
                this.RaisePropertyChanged("Ussist");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://datcontrib.Schema_datcontrib_rice")]
    public partial class ICE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ICERESULTADO rESULTADOField;
        
        private ICERESPUESTA rESPUESTAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ICERESULTADO RESULTADO {
            get {
                return this.rESULTADOField;
            }
            set {
                this.rESULTADOField = value;
                this.RaisePropertyChanged("RESULTADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ICERESPUESTA RESPUESTA {
            get {
                return this.rESPUESTAField;
            }
            set {
                this.rESPUESTAField = value;
                this.RaisePropertyChanged("RESPUESTA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://datcontrib.Schema_datcontrib_rice")]
    public partial class ICERESULTADO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int eSTADOField;
        
        private long cODIGOField;
        
        private string dESCRIPCIONField;
        
        private string iD_RESPUESTAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
                this.RaisePropertyChanged("ESTADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long CODIGO {
            get {
                return this.cODIGOField;
            }
            set {
                this.cODIGOField = value;
                this.RaisePropertyChanged("CODIGO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ID_RESPUESTA {
            get {
                return this.iD_RESPUESTAField;
            }
            set {
                this.iD_RESPUESTAField = value;
                this.RaisePropertyChanged("ID_RESPUESTA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://datcontrib.Schema_datcontrib_rice")]
    public partial class ICERESPUESTA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ICERESPUESTARESP_BODY rESP_BODYField;
        
        private ICERESPUESTARESP_HDR rESP_HDRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ICERESPUESTARESP_BODY RESP_BODY {
            get {
                return this.rESP_BODYField;
            }
            set {
                this.rESP_BODYField = value;
                this.RaisePropertyChanged("RESP_BODY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ICERESPUESTARESP_HDR RESP_HDR {
            get {
                return this.rESP_HDRField;
            }
            set {
                this.rESP_HDRField = value;
                this.RaisePropertyChanged("RESP_HDR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://datcontrib.Schema_datcontrib_rice")]
    public partial class ICERESPUESTARESP_BODY : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eSTADOField;
        
        private string nOMBREField;
        
        private string aP_PATERNOField;
        
        private string aP_MATERNOField;
        
        private string rAZON_SOCIALField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
                this.RaisePropertyChanged("ESTADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NOMBRE {
            get {
                return this.nOMBREField;
            }
            set {
                this.nOMBREField = value;
                this.RaisePropertyChanged("NOMBRE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string AP_PATERNO {
            get {
                return this.aP_PATERNOField;
            }
            set {
                this.aP_PATERNOField = value;
                this.RaisePropertyChanged("AP_PATERNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string AP_MATERNO {
            get {
                return this.aP_MATERNOField;
            }
            set {
                this.aP_MATERNOField = value;
                this.RaisePropertyChanged("AP_MATERNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string RAZON_SOCIAL {
            get {
                return this.rAZON_SOCIALField;
            }
            set {
                this.rAZON_SOCIALField = value;
                this.RaisePropertyChanged("RAZON_SOCIAL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://datcontrib.Schema_datcontrib_rice")]
    public partial class ICERESPUESTARESP_HDR : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eSTADOField;
        
        private string gLOSAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
                this.RaisePropertyChanged("ESTADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string GLOSA {
            get {
                return this.gLOSAField;
            }
            set {
                this.gLOSAField = value;
                this.RaisePropertyChanged("GLOSA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ope_prt_sii_datcontrib", WrapperNamespace="http://minvu/ice/sii", IsWrapped=true)]
    public partial class ope_prt_sii_datcontribRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SII.schemas.Schema_datcontrib_conice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://SII.schemas.Schema_datcontrib_conice")]
        public Minvu.Snat.IData.SI.DatContrib DatContrib;
        
        public ope_prt_sii_datcontribRequest() {
        }
        
        public ope_prt_sii_datcontribRequest(Minvu.Snat.IData.SI.DatContrib DatContrib) {
            this.DatContrib = DatContrib;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ope_prt_sii_datcontribResponse", WrapperNamespace="http://minvu/ice/sii", IsWrapped=true)]
    public partial class ope_prt_sii_datcontribResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://datcontrib.Schema_datcontrib_rice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://datcontrib.Schema_datcontrib_rice")]
        public Minvu.Snat.IData.SI.ICE ICE;
        
        public ope_prt_sii_datcontribResponse() {
        }
        
        public ope_prt_sii_datcontribResponse(Minvu.Snat.IData.SI.ICE ICE) {
            this.ICE = ICE;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SII_orc_datcontrib_prt_sii_datcontribSoapChannel : Minvu.Snat.IData.SI.SII_orc_datcontrib_prt_sii_datcontribSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SII_orc_datcontrib_prt_sii_datcontribSoapClient : System.ServiceModel.ClientBase<Minvu.Snat.IData.SI.SII_orc_datcontrib_prt_sii_datcontribSoap>, Minvu.Snat.IData.SI.SII_orc_datcontrib_prt_sii_datcontribSoap {
        
        public SII_orc_datcontrib_prt_sii_datcontribSoapClient() {
        }
        
        public SII_orc_datcontrib_prt_sii_datcontribSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SII_orc_datcontrib_prt_sii_datcontribSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SII_orc_datcontrib_prt_sii_datcontribSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SII_orc_datcontrib_prt_sii_datcontribSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Minvu.Snat.IData.SI.ope_prt_sii_datcontribResponse Minvu.Snat.IData.SI.SII_orc_datcontrib_prt_sii_datcontribSoap.ope_prt_sii_datcontrib(Minvu.Snat.IData.SI.ope_prt_sii_datcontribRequest request) {
            return base.Channel.ope_prt_sii_datcontrib(request);
        }
        
        public Minvu.Snat.IData.SI.ICE ope_prt_sii_datcontrib(Minvu.Snat.IData.SI.DatContrib DatContrib) {
            Minvu.Snat.IData.SI.ope_prt_sii_datcontribRequest inValue = new Minvu.Snat.IData.SI.ope_prt_sii_datcontribRequest();
            inValue.DatContrib = DatContrib;
            Minvu.Snat.IData.SI.ope_prt_sii_datcontribResponse retVal = ((Minvu.Snat.IData.SI.SII_orc_datcontrib_prt_sii_datcontribSoap)(this)).ope_prt_sii_datcontrib(inValue);
            return retVal.ICE;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Minvu.Snat.IData.SI.ope_prt_sii_datcontribResponse> Minvu.Snat.IData.SI.SII_orc_datcontrib_prt_sii_datcontribSoap.ope_prt_sii_datcontribAsync(Minvu.Snat.IData.SI.ope_prt_sii_datcontribRequest request) {
            return base.Channel.ope_prt_sii_datcontribAsync(request);
        }
        
        public System.Threading.Tasks.Task<Minvu.Snat.IData.SI.ope_prt_sii_datcontribResponse> ope_prt_sii_datcontribAsync(Minvu.Snat.IData.SI.DatContrib DatContrib) {
            Minvu.Snat.IData.SI.ope_prt_sii_datcontribRequest inValue = new Minvu.Snat.IData.SI.ope_prt_sii_datcontribRequest();
            inValue.DatContrib = DatContrib;
            return ((Minvu.Snat.IData.SI.SII_orc_datcontrib_prt_sii_datcontribSoap)(this)).ope_prt_sii_datcontribAsync(inValue);
        }
    }
}
